### ISSUE TITLE
Error occurred during infeed/outfeed when training ResNet on custom data

### ISSUE THREAD

**Issue by XinshaoWang** [tensorflow/tpu#132]
I0530 14:40:12.307559 140105226974976 tf_logging.py:116] Enqueue next (100) batch(es) of data to infeed.
I0530 14:40:12.308238 140105226974976 tf_logging.py:116] Dequeue next (100) batch(es) of data from outfeed.
W0530 14:40:14.046279 140104498669312 tf_logging.py:126] 

Error occurred during infeed/outfeed.  This may be due to a compile error in the main session.  Waiting for a short time for the main session to come back.

End of sequence
	 [[Node: input_pipeline_task0/IteratorGetNext = IteratorGetNext[_class=["loc:@input_pipeline_task0/InfeedQueue/split/1"], output_shapes=[[1024,224,224,3], [1024]], output_types=[DT_FLOAT, DT_INT32], _device="/job:tpu_worker/replica:0/task:0/device:CPU:0"](input_pipeline_task0/OneShotIterator)]]

Caused by op u'input_pipeline_task0/IteratorGetNext', defined at:
  File "resnet_main_webface_V01.py", line 508, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "resnet_main_webface_V01.py", line 440, in main
    input_fn=ImageNetInput(True), max_steps=next_checkpoint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 352, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 812, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 793, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2065, in _model_fn
    input_holders.generate_infeed_enqueue_ops_and_dequeue_fn())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1149, in generate_infeed_enqueue_ops_and_dequeue_fn
    self._invoke_input_fn_and_record_structure())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1202, in _invoke_input_fn_and_record_structure
    self._batch_axis, host_device))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 918, in generate_per_host_enqueue_ops_fn_for_host
    inputs = _Inputs.from_input_fn(input_fn())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2036, in _input_fn
    return input_fn(**kwargs)
  File "resnet_main_webface_V01.py", line 255, in __call__
    images, labels = dataset.make_one_shot_iterator().get_next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 330, in get_next
    name=name)), self._output_types,
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 866, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): End of sequence
	 [[Node: input_pipeline_task0/IteratorGetNext = IteratorGetNext[_class=["loc:@input_pipeline_task0/InfeedQueue/split/1"], output_shapes=[[1024,224,224,3], [1024]], output_types=[DT_FLOAT, DT_INT32], _device="/job:tpu_worker/replica:0/task:0/device:CPU:0"](input_pipeline_task0/OneShotIterator)]]

E0530 14:40:19.053837 140104481883904 tf_logging.py:106] Feed error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 666, in _run_infeed
    session.run(self._enqueue_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
OutOfRangeError: End of sequence
	 [[Node: input_pipeline_task0/IteratorGetNext = IteratorGetNext[_class=["loc:@input_pipeline_task0/InfeedQueue/split/1"], output_shapes=[[1024,224,224,3], [1024]], output_types=[DT_FLOAT, DT_INT32], _device="/job:tpu_worker/replica:0/task:0/device:CPU:0"](input_pipeline_task0/OneShotIterator)]]

Caused by op u'input_pipeline_task0/IteratorGetNext', defined at:
  File "resnet_main_webface_V01.py", line 508, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "resnet_main_webface_V01.py", line 440, in main
    input_fn=ImageNetInput(True), max_steps=next_checkpoint)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 352, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 812, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 793, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2065, in _model_fn
    input_holders.generate_infeed_enqueue_ops_and_dequeue_fn())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1149, in generate_infeed_enqueue_ops_and_dequeue_fn
    self._invoke_input_fn_and_record_structure())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1202, in _invoke_input_fn_and_record_structure
    self._batch_axis, host_device))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 918, in generate_per_host_enqueue_ops_fn_for_host
    inputs = _Inputs.from_input_fn(input_fn())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2036, in _input_fn
    return input_fn(**kwargs)
  File "resnet_main_webface_V01.py", line 255, in __call__
    images, labels = dataset.make_one_shot_iterator().get_next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 330, in get_next
    name=name)), self._output_types,
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 866, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): End of sequence
	 [[Node: input_pipeline_task0/IteratorGetNext = IteratorGetNext[_class=["loc:@input_pipeline_task0/InfeedQueue/split/1"], output_shapes=[[1024,224,224,3], [1024]], output_types=[DT_FLOAT, DT_INT32], _device="/job:tpu_worker/replica:0/task:0/device:CPU:0"](input_pipeline_task0/OneShotIterator)]]

E0530 14:40:19.054299 140104481883904 tf_logging.py:106] Closing session.  A RuntimeError should follow.
I0530 14:40:25.495778 140105226974976 tf_logging.py:116] An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. Error: Socket closed
I0530 14:40:25.496537 140105226974976 tf_logging.py:116] Graph was finalized.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 647, in _cancel_session
    session.close()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 702, in close
    tf_session.TF_CloseDeprecatedSession(self._session, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
UnavailableError: Socket closed

**Comment by saeta** [comment]
Hi @XinshaoWang!

Thanks for reaching out. While the error message seems very intimidating, I think the following is the real underlying error:

```
OutOfRangeError (see above for traceback): End of sequence
[[Node: input_pipeline_task0/IteratorGetNext = IteratorGetNext_class=["loc:@input_pipeline_task0/InfeedQueue/split/1"], output_shapes=[[1024,224,224,3], [1024]], output_types=[DT_FLOAT, DT_INT32], _device="/job:tpu_worker/replica:0/task:0/device:CPU:0"]]
```

In short, it appears as if your input pipeline reached its end-of-sequence. Be sure to check that: (1) your TPU has access to training data (e.g. GCS bucket), (2) you don't have a typo in the path (believe me, I've done this more often than I'd like to admit!), and (3) ensure your data set is either large or you have a `dataset.repeat()` in there to ensure your training data doesn't run out before your TPU has completed the configured number of steps.

If there are further issues, please don't hesitate to re-open!

Hope this helps,
-Brennan

**Comment by JadenLy** [comment]
@XinshaoWang Have you found the problem here? 

I have the same problem training an inception_v3 model with my own dataset. I have modified number of training and evaluation images as well as number of classes according to my own dataset. I read from other posts but found that there is no `eval_steps` in the scripts anymore. According to this post, I found that `dataset.repeat()` has been implemented by default. So I wonder if there is any potential cause here. Thanks~

**Comment by jasonge27** [comment]
@JadenLy  I ran into a similar problem and found out it was actually TPU read permission for the GCS bucket. See details here https://cloud.google.com/tpu/docs/storage-buckets. I set up ACL permission once for the storage bucket folder but the permission is not automatically granted to new tfrecord files coming into the folder, and I was trying to train on the new tfrecord :)

**Comment by JadenLy** [comment]
@jasonge27 Thanks for your help here. I referred to the document you mentioned and set up the permissions accordingly. I used `gustil` to copy all tfrecord files to the bucket storage. However, I still have the same error messages.

**Comment by jasonge27** [comment]
@JadenLy I had to run the following commands to set up permission. Not just gsutil copy
gsutil acl -r ch -u service-xxxxxxxx@cloud-tpu.iam.gserviceaccount.com:READER gs://bucket-name
gsutil acl -r ch -u service-xxxxx@cloud-tpu.iam.gserviceaccount.com:WRITER gs://bucket-name

**Comment by Rajjae** [comment]
I've had a similar error when the tfrecords were stored on the GCE connected to the TPU.
To solve it I moved the tfrecords to bucket storage and granted the tpu access to this bucket from the console as described in this link: https://cloud.google.com/tpu/docs/storage-buckets.

Thank you @JadenLy and @jasonge27 for pointing in the right direction to solve this error.
