### ISSUE TITLE
UnavailableError: Socket closed : amoeba_net

### ISSUE THREAD

**Issue by karandwivedi42** [tensorflow/tpu#146]
Using:

```
code: experimental/amoeba_net/amoeba_net.py
branch: r1.8
```

I am able to train the model using `amoeba_net_x` (`x` = `a,b,c,d`). However, when I change the cell to a custom cell (keeping all other parameters same), I am unable to train the model. The training starts normally but I keep getting `Socket closed` error during the training. (most of the cycles fail with this error, some don't)

Complete Logs:
```
I0706 19:04:54.077939 140690244269824 tf_logging.py:116] Graph was finalized.
I0706 19:04:54.352663 140690244269824 tf_logging.py:116] Restoring parameters from <data_dir>/model.ckpt-6000
I0706 19:07:55.526499 140690244269824 tf_logging.py:116] Running local_init_op.
I0706 19:08:00.698863 140690244269824 tf_logging.py:116] Done running local_init_op.
I0706 19:08:27.570785 140690244269824 tf_logging.py:116] Init TPU system
I0706 19:08:44.705221 140690244269824 tf_logging.py:116] Start infeed thread controller
I0706 19:08:44.705890 140687278339840 tf_logging.py:116] Starting infeed thread controller.
I0706 19:08:44.706137 140690244269824 tf_logging.py:116] Start outfeed thread controller
I0706 19:08:44.706412 140687290922752 tf_logging.py:116] Starting outfeed thread controller.
I0706 19:08:55.460019 140690244269824 tf_logging.py:116] Enqueue next (500) batch(es) of data to infeed.
I0706 19:08:55.460402 140690244269824 tf_logging.py:116] Dequeue next (500) batch(es) of data from outfeed.
W0706 19:21:49.613796 140687278339840 tf_logging.py:126] 

Error occurred during infeed/outfeed.  This may be due to a compile error in the main session.  Waiting for a short time for the main session to come back.

Socket closed
I0706 19:21:49.615422 140690244269824 tf_logging.py:116] An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. Error: Socket closed
W0706 19:21:49.616436 140687290922752 tf_logging.py:126] 

Error occurred during infeed/outfeed.  This may be due to a compile error in the main session.  Waiting for a short time for the main session to come back.

Socket closed
E0706 19:21:54.622838 140687519512320 tf_logging.py:106] Feed error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 447, in _run_outfeed
    session.run(self._dequeue_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
UnavailableError: Socket closed

E0706 19:21:54.623138 140687519512320 tf_logging.py:106] Closing session.  A RuntimeError should follow.
I0706 19:21:55.618206 140690244269824 tf_logging.py:116] Graph was finalized.
I0706 19:21:55.947227 140690244269824 tf_logging.py:116] Restoring parameters from <data_dir>/model.ckpt-6000
```
and it reapeats so on

**Comment by sb2nov** [comment]
Does this happen consistently if you recreate the TPU? If yes, could you try reducing the batch size and see anything changes?

**Comment by karandwivedi42** [comment]
Yes, I tested that the TPU works (using `cloud-tpu.py` script from the quickstart).

The problem remains even after reducing `batch_size`, `save_checkpoint_steps` and `reduction_size`.

**Comment by karandwivedi42** [comment]
@leoybkim now I am getting this error https://github.com/tensorflow/tpu/issues/152

**Comment by vishalsubbiah** [comment]
So, I've been trying to run a simple 2 hidden layer FN on the mnist data. I get the same error, when I use all the features. But If I only use 631 or lesser features, it no longer gives the error. Is there a reason for this? (The number of samples doesn't seem to affect the number of features I can use.)

**Comment by aman2930** [comment]
I hope this issue is fixed. So closing it now. Feel free to reopen it if still reproducing.
