### ISSUE TITLE
Very slow training when following resnet tutorial, possibly because of file_cache error

### ISSUE THREAD

**Issue by mlucy** [tensorflow/tpu#156]
I'm following the instructions in https://cloud.google.com/tpu/docs/tutorials/resnet , and I get about 40 examples/sec of throughput:

```
I0724 03:44:09.470874 140435012744960 tf_logging.py:115] loss = 1.5828536, step = 200 (2471.960 sec)
I0724 03:44:09.472132 140435012744960 tf_logging.py:115] global_step/sec: 0.0404537
I0724 03:44:09.942822 140435012744960 tf_logging.py:115] examples/sec: 41.4246
```

The following error occurs earlier in the output:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
```

Here's the whole log, if it's helpful:
```
mlucy@mlucy:/usr/share/tpu/models/official/resnet$ python resnet_main.py   --tpu=$TPU_NAME   --data_dir=$DATA_DIR   --model_dir=${STORAGE_BUCKET}/images/generic/resnet
W0724 02:39:43.722238 140435012744960 __init__.py:44] file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
W0724 02:39:43.877512 140435012744960 tf_logging.py:125] Estimator's model_fn (<function resnet_model_fn at 0x7fb975b9ec08>) includes params argument, but params are not passed to Estimator.
I0724 02:39:43.878710 140435012744960 tf_logging.py:115] Using config: {'_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
cluster_def {
  job {
    name: "worker"
    tasks {
      value: "10.240.1.2:8470"
    }
  }
}
, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_train_distribute': None, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fb97528d450>, '_model_di
r': 'gs://basilica/images/generic/resnet', '_save_checkpoints_steps': 600, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tpu_config': TPUConfig(iterations_per_loop=10
0, num_shards=8, computation_shape=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None), '_tf_random_seed': None, '_save_summary_steps': 100, '_device_fn': None, '_clust
er': <tensorflow.contrib.cluster_resolver.python.training.tpu_cluster_resolver.TPUClusterResolver object at 0x7fb9758ce290>, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': None, '_eval
uation_master': u'grpc://10.240.1.2:8470', '_global_id_in_cluster': 0, '_master': u'grpc://10.240.1.2:8470'}
I0724 02:39:43.878993 140435012744960 tf_logging.py:115] _TPUContext: eval_on_tpu True
I0724 02:39:43.879216 140435012744960 tf_logging.py:115] Precision: bfloat16
I0724 02:39:44.232106 140435012744960 tf_logging.py:115] Training for 112603 steps (90.00 epochs in total). Current step 0.
I0724 02:39:44.529622 140435012744960 tf_logging.py:115] Querying Tensorflow master (grpc://10.240.1.2:8470) for TPU system metadata.
2018-07-24 02:39:44.531309: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:349] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
I0724 02:39:44.601207 140435012744960 tf_logging.py:115] Found TPU system:
I0724 02:39:44.601444 140435012744960 tf_logging.py:115] *** Num TPU Cores: 8
I0724 02:39:44.601916 140435012744960 tf_logging.py:115] *** Num TPU Workers: 1
I0724 02:39:44.602014 140435012744960 tf_logging.py:115] *** Num TPU Cores Per Worker: 8
I0724 02:39:44.602096 140435012744960 tf_logging.py:115] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, -1)
I0724 02:39:44.602328 140435012744960 tf_logging.py:115] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184)
I0724 02:39:44.602428 140435012744960 tf_logging.py:115] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_GPU:0, XLA_GPU, 17179869184)
I0724 02:39:44.602513 140435012744960 tf_logging.py:115] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 17179869184)
I0724 02:39:44.602597 140435012744960 tf_logging.py:115] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 17179869184)
I0724 02:39:44.602674 140435012744960 tf_logging.py:115] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 17179869184)
I0724 02:39:44.602754 140435012744960 tf_logging.py:115] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 17179869184)
I0724 02:39:44.602828 140435012744960 tf_logging.py:115] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 17179869184)
I0724 02:39:44.602900 140435012744960 tf_logging.py:115] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 17179869184)
I0724 02:39:44.602974 140435012744960 tf_logging.py:115] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 17179869184)
I0724 02:39:44.603046 140435012744960 tf_logging.py:115] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 17179869184)
I0724 02:39:44.603120 140435012744960 tf_logging.py:115] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 17179869184)
I0724 02:39:44.616926 140435012744960 tf_logging.py:115] Calling model_fn.
I0724 02:39:53.176857 140435012744960 tf_logging.py:115] Create CheckpointSaverHook.
I0724 02:39:53.386686 140435012744960 tf_logging.py:115] Done calling model_fn.
I0724 02:39:58.610001 140435012744960 tf_logging.py:115] TPU job name worker
I0724 02:39:59.607289 140435012744960 tf_logging.py:115] Graph was finalized.
I0724 02:40:02.081937 140435012744960 tf_logging.py:115] Running local_init_op.
I0724 02:40:02.220175 140435012744960 tf_logging.py:115] Done running local_init_op.
I0724 02:40:09.082227 140435012744960 tf_logging.py:115] Saving checkpoints for 0 into gs://basilica/images/generic/resnet/model.ckpt.
I0724 02:40:16.276730 140435012744960 tf_logging.py:115] Installing graceful shutdown hook.
2018-07-24 02:40:16.277159: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:349] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
I0724 02:40:16.281248 140435012744960 tf_logging.py:115] Creating heartbeat manager for ['/job:tpu_worker/replica:0/task:0/device:CPU:0', '/job:tpu_worker/replica:0/task:0/device:XLA_CPU:0']
W0724 02:40:16.290678 140435012744960 tf_logging.py:120] Worker heartbeats not supported by all workers.  No failure handling will be enabled.
I0724 02:40:16.290915 140435012744960 tf_logging.py:115] Init TPU system
I0724 02:40:24.871825 140433930057472 tf_logging.py:115] Starting infeed thread controller.
I0724 02:40:24.872430 140433921664768 tf_logging.py:115] Starting outfeed thread controller.
I0724 02:40:25.006061 140435012744960 tf_logging.py:115] Enqueue next (100) batch(es) of data to infeed.
I0724 02:40:25.006603 140435012744960 tf_logging.py:115] Dequeue next (100) batch(es) of data from outfeed.
I0724 03:02:57.510490 140435012744960 tf_logging.py:115] loss = 1.4244831, step = 100
I0724 03:02:57.512698 140435012744960 tf_logging.py:115] Enqueue next (100) batch(es) of data to infeed.
I0724 03:02:57.512928 140435012744960 tf_logging.py:115] Dequeue next (100) batch(es) of data from outfeed.
I0724 03:44:09.470874 140435012744960 tf_logging.py:115] loss = 1.5828536, step = 200 (2471.960 sec)
I0724 03:44:09.472132 140435012744960 tf_logging.py:115] global_step/sec: 0.0404537
I0724 03:44:09.942822 140435012744960 tf_logging.py:115] examples/sec: 41.4246
I0724 03:44:09.944439 140435012744960 tf_logging.py:115] Enqueue next (100) batch(es) of data to infeed.
I0724 03:44:09.944626 140435012744960 tf_logging.py:115] Dequeue next (100) batch(es) of data from outfeed.
```

**Comment by mlucy** [comment]
I tried running the profiler, and it says:

```
Host idle time (lower is better): 33.0%
TPU idle time (lower is better): 0.0%
Utilization of TPU Matrix Units (higher is better): 0.6%
```

**Comment by mlucy** [comment]
I looked into this a little more, and it seems like loading the images from GCS is the bottleneck.  When I make the tensorflow code cache the images after loading them from GCS, performance jumps to ~3k examples/sec.

Is there a better way to be doing this?

**Comment by yguo0905** [comment]
What training data and tensorflow version are you using?

**Comment by mlucy** [comment]
I'm using the data at gs://cloud-tpu-test-datasets/fake_imagenet , TensorFlow version 1.9 .

**Comment by yguo0905** [comment]
> Is there a better way to be doing this?

You shouldn't need to do anything - there seems to be an issue on this fake dataset for TF 1.9.

Before the issue is addressed, you could use TF 1.8.

**Comment by yguo0905** [comment]
The fake data has been fixed. Please try it again with TF 1.9.

**Comment by mlucy** [comment]
Retested with 1.9, works fine now.

Thanks again.
