### ISSUE TITLE
[Retinanet Training] TypeError: Parameter does not match pattern

### ISSUE THREAD

**Issue by adreo00** [tensorflow/tpu#168]
I ran this code on a TPU using python 3.5 and tensorflow 1.9. 
I was using the [retinanet TPU tutorial](https://cloud.google.com/tpu/docs/tutorials/retinanet) as a template, substituting in my own data.

This was my input:
```
RESNET_CHECKPOINT=gs://cloud-tpu-artifacts/resnet/resnet-nhwc-2018-02-07/model.ckpt-112603
STORAGE_BUCKET=gs://uxml_store
MODEL_DIR=${STORAGE_BUCKET}/retinanet

sudo pip3 install cython matplotlib pycocotools
sudo apt-get install python3-tk

python3 tpu/models/official/retinanet/retinanet_main.py \
 --tpu=retinanet-tpu \
 --train_batch_size=8 \
 --training_file_pattern=${STORAGE_BUCKET}/tfrecords/train.tfrecord \
 --resnet_checkpoint=${RESNET_CHECKPOINT} \
 --model_dir=${MODEL_DIR} \
 --hparams=image_size=640 \
 --num_examples_per_epoch=6400 \
 --num_epochs=1
```
I'm encountering the following error.
```
Traceback (most recent call last):
  File "tpu/models/official/retinanet/retinanet_main.py", line 296, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tpu/models/official/retinanet/retinanet_main.py", line 107, in main
    tpu_grpc_url = tpu_cluster_resolver.get_master()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/cluster_resolver/python/training/tpu_cluster_resolver.py", line 225, in get_master
    return self.master()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/cluster_resolver/python/training/tpu_cluster_resolver.py", line 218, in master
    job_tasks = self.cluster_spec().job_tasks(self._job_name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/cluster_resolver/python/training/tpu_cluster_resolver.py", line 255, in cluster_spec
    request = self._service.projects().locations().nodes().get(name=full_name)
  File "/usr/local/lib/python3.5/dist-packages/googleapiclient/discovery.py", line 742, in method
    (name, pvalue, regex))
TypeError: Parameter "name" value "projects//locations/us-east1-b/nodes/retinanet-tpu" does not match the pattern "^projects/[^/]+/locations/[^/]+/nodes/[^/]+$"
```
I'm guessing this has something to do with the project section of the name parameter being blank, because of the project**//**locations, but I can't find anyway to change this. Any ideas?

**Comment by adreo00** [comment]
The error was caused by the command being executed in the cloud shell instead of on the compute VM.
