### ISSUE TITLE
[Retinanet Training] TypeError: batch() got an unexpected keyword argument 'drop_remainder'

### ISSUE THREAD

**Issue by meteortwinkle** [tensorflow/tpu#169]
I ran this code on a TPU using python 2.7 and tensorflow 1.9.
I was using the retinanet TPU tutorial as a template, substituting in my own data.

RESNET_CHECKPOINT=gs://cloud-tpu-artifacts/resnet/resnet-nhwc-2018-02-07/model.ckpt-112603
MODEL_DIR=${GCS_BUCKET}/retinanet/retinanet-model

python tpu/models/official/retinanet/retinanet_main.py \
 --tpu=${TPU_NAME} \
 --train_batch_size=64 \
 --training_file_pattern=${GCS_BUCKET}/data/coco/train-* \
 --resnet_checkpoint=${RESNET_CHECKPOINT} \
 --model_dir=${MODEL_DIR} \
 --hparams=image_size=640 \
 --num_examples_per_epoch=6400 \
 --num_epochs=1

This is my error:
Traceback (most recent call last):
  File "tpu/models/official/retinanet/retinanet_main.py", line 295, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tpu/models/official/retinanet/retinanet_main.py", line 171, in main
    FLAGS.train_batch_size))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 366, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1119, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1132, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1992, in _call_model_fn
    features, labels, mode, config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 1107, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2212, in _model_fn
    input_holders.generate_infeed_enqueue_ops_and_dequeue_fn())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1001, in generate_infeed_enqueue_ops_and_dequeue_fn
    self._invoke_input_fn_and_record_structure())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1059, in _invoke_input_fn_and_record_structure
    self._inputs_structure_recorder, host_device, host_id))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 771, in generate_per_host_v2_enqueue_ops_fn_for_host
    inputs = _Inputs.from_input_fn(input_fn(user_context))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2163, in _input_fn
    return input_fn(**kwargs)
  File "/home/aaflier/tpu/models/official/retinanet/dataloader.py", line 353, in __call__
    dataset = dataset.batch(batch_size, drop_remainder=True)
TypeError: batch() got an unexpected keyword argument 'drop_remainder'

Has anyone encountered this question? It's like an incompatible problem,but I'm not sure.

**Comment by saeta** [comment]
@meteortwinkle If you're using TF 1.9, be sure to use the appropriate branch of this repository (<https://github.com/tensorflow/tpu/tree/r1.9>). In the TF 1.9 branch, we use [`tf.data.contrib.map_and_batch(drop_remainder=True)`](https://github.com/tensorflow/tpu/blob/r1.9/models/official/resnet/imagenet_input.py#L173) which works, as well as [`tf.data.contrib.batch_and_drop_remainder(...)`](https://github.com/tensorflow/tpu/blob/r1.9/models/official/resnet/imagenet_input.py#L198). As @thmnee correctly mentioned, in TF 1.10 `dataset.batch()` added support for `drop_remainder=True`. The master branch reflects the latest and greatest version. :-) Please don't hesitate to reach out if you encounter any further issues!

**Comment by meteortwinkle** [comment]
@thmnee @saeta 
OK, thanks a lot.
