### ISSUE TITLE
Error running models in experimental/keras

### ISSUE THREAD

**Issue by Hoiy** [tensorflow/tpu#196]
I was trying to run minist example from `experimental/keras` and got the following error.

```> python3 mnist.py --tpu=my-tpu```
```
Mode: TPU
Using real data
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
Traceback (most recent call last):
  File "mnist.py", line 122, in <module>
    tf.app.run()
  File ".../.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "mnist.py", line 98, in main
    strategy = tf.contrib.tpu.TPUDistributionStrategy(
AttributeError: module 'tensorflow.contrib.tpu' has no attribute 'TPUDistributionStrategy'
```

After that, I upgraded my VM to tensorflow 1.11.0rc2 with `pip3 install -U tensorflow==1.11.0rc2`. Running the same command again and got another error.

```Mode: TPU
Using real data
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
INFO:tensorflow:Querying Tensorflow master (grpc://10.240.1.2:8470) for TPU system metadata.
2018-09-23 16:06:20.877643: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:349] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
INFO:tensorflow:Found TPU system:
INFO:tensorflow:*** Num TPU Cores: 8
INFO:tensorflow:*** Num TPU Workers: 1
INFO:tensorflow:*** Num TPU Cores Per Worker: 8
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, -1, 743002427051527235)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 15013993383576869908)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_GPU:0, XLA_GPU, 17179869184, 3130476976480352417)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 17179869184, 16597017996402135163)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 17179869184, 3794872272132273943)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 17179869184, 846334726384924258)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 17179869184, 11930838816625091439)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 17179869184, 8442147069015718247)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 17179869184, 16200388111622413380)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 17179869184, 4749546596775377587)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 17179869184, 3825423151401653496)
INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 17179869184, 8009678287201440362)
WARNING:tensorflow:tpu_model (from tensorflow.contrib.tpu.python.tpu.keras_support) is experimental and may change or be removed at any time, and without warning.
INFO:tensorflow:Connecting to: grpc://10.240.1.2:8470
Train on 60000 samples, validate on 10000 samples
Epoch 1/12
INFO:tensorflow:New input shapes; (re-)compiling: mode=train, [TensorSpec(shape=(16, 28, 28, 1), dtype=tf.float32, name='conv2d_input0'), TensorSpec(shape=(16, 10), dtype=tf.float32, name='dense_1_target0')]
INFO:tensorflow:Overriding default placeholder.
INFO:tensorflow:Remapping placeholder for conv2d_input
INFO:tensorflow:Started compiling
Traceback (most recent call last):
  File ".../.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1292, in _do_call
    return fn(*args)
  File ".../.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1275, in _run_fn
    self._extend_graph()
  File ".../.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1312, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: metrics/acc/Cast = Cast[DstT=DT_FLOAT, SrcT=DT_BOOL, Truncate=false, _tpu_replicate="cluster"](metrics/acc/Equal). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mnist.py", line 122, in <module>
    tf.app.run()
  File ".../.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "mnist.py", line 114, in main
    validation_data=(x_test, y_test))
  File ".../.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 1285, in fit
    **kwargs)
  File ".../.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 1399, in _pipeline_fit
    validation_steps=validation_steps)
  File ".../.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 1502, in _pipeline_fit_loop
    epoch_logs=epoch_logs)
  File ".../.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 1558, in _pipeline_fit_loop_sample_wise
    next_step_inputs=ins_batch)
  File ".../.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 1077, in pipeline_run
    next_input_specs, next_step_infeed_manager)
  File ".../.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 919, in _tpu_model_ops_for_input_specs
    self._test_model_compiles(new_tpu_model_ops)
  File ".../.local/lib/python3.5/site-packages/tensorflow/contrib/tpu/python/tpu/keras_support.py", line 859, in _test_model_compiles
    result = K.get_session().run(tpu_model_ops.compile_op)
  File ".../.local/lib/python3.5/site-packages/tensorflow/python/keras/backend.py", line 465, in get_session
    _initialize_variables(session)
  File ".../.local/lib/python3.5/site-packages/tensorflow/python/keras/backend.py", line 719, in _initialize_variables
    [variables_module.is_variable_initialized(v) for v in candidate_vars])
  File ".../.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File ".../.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File ".../.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File ".../.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: metrics/acc/Cast = Cast[DstT=DT_FLOAT, SrcT=DT_BOOL, Truncate=false, _tpu_replicate="cluster"](metrics/acc/Equal). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
```

I wonder if this error is caused by TPU having only version 1.9.1 of tensorflow. Are there any way I could upgrade the version of tensorflow in TPU? I would really love to try out running keras model on TPU. Thanks.

**Comment by mikeh9** [comment]
I got the same error as @Hoiy with tensorflow 1.9. I upgraded VM to tensorflow v1.10 (stable). Then the VM hangs on the last item shown below. I have restarted it 3 times with the same result.

Installing collected packages: gast, six, absl-py, termcolor, wheel, grpcio, markdown, numpy, setuptools, protobuf, werkzeug, tensorboard, astor, tensorflow
Successfully installed absl-py-0.5.0 astor-0.7.1 gast-0.2.0 grpcio-1.15.0 markdown-3.0 numpy-1.15.1 protobuf-3.6.1 setuptools-40.2.0 six-1.11.0 tensorboard-1.10.0 tensorflow-1.10.1 termcolor-1.1.0 werkzeug-0.14.1 wheel-0.31.1
~/tpu/models/experimental/keras$ python3 mnist.py --use_tpu=True --tpu=mikeh9hamilmc
Mode: TPU
Using real data
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
INFO:tensorflow:Detected old TPUStrategy API.
WARNING:tensorflow:tpu_model (from tensorflow.contrib.tpu.python.tpu.keras_support) is experimental and may change or be removed at any time, and without warning.
2018-09-25 22:25:34.504409: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

**Comment by mikeh9** [comment]
I upgraded to tensorflow v1.11.0rc2 and I got the same error as @Hoiy ending with:

tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: metrics/acc/Cast = Cast[DstT=DT_FLOAT, SrcT=DT_BOOL, Truncate=false, _tpu_replicate="cluster"](metrics/acc/Equal). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

**Comment by Hoiy** [comment]
Not sure why I missed this but I finally get it working by creating vm+tpu in tf-version 1.11 with `ctpu up -tf-version=1.11 ...` command :D

**Comment by mikeh9** [comment]
Didn't know about that flag. I will give it a try.
