### ISSUE TITLE
Unable to train deeplab on tpu, probably due to incompatibility issues

### ISSUE THREAD

**Issue by limslarmo** [tensorflow/tpu#257]
I need to train a semantic segmentation model with my own dataset on TPU and I'm experimenting with this deeplab. 
I'm following the instructions here[tpu/models/experimental/deeplab/README.md](tpu/models/experimental/deeplab/README.md), but the program ran into a ton of unexpected issues. Me and three friends tried independently but none was able to get it to work. We're all new to this field, so I wonder if we misunderstood something. 

On cloud vm, I tried to execute the following line provided in README.md:
```
python main.py \
--mode='train' \
--num_shards=8 \
--alsologtostderr=true \
--model_dir=${MODEL_DIR} \
--dataset_dir=${DATASET_DIR} \
--init_checkpoint=${INIT_CHECKPOINT} \
--model_variant=resnet_v1_101_beta \
--image_pyramid=1. \
--aspp_with_separable_conv=false \
--multi_grid=1 \
--multi_grid=2 \
--multi_grid=4 \
--decoder_use_separable_conv=false
```
where I set DATASET_DIR=/.../datasets/pascal_voc_seg/tfrecord, 
INIT_CHECKPOINT=/.../datasets/pascal_voc_seg/deeplabv3_pascal_train_aug
MODEL_DIR=/.../models/research/deeplab/

I got this error:
```
Traceback (most recent call last):
  File "main.py", line 304, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 119, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "/home/al/.local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 625, in __call__
    unknown_flags, unparsed_args = self._parse_args(args, known_only)
  File "/home/al/.local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 761, in _parse_args
    flag.parse(value)
  File "/home/al/.local/lib/python2.7/site-packages/absl/flags/_flag.py", line 151, in parse
    self.value = self._parse(argument)
  File "/home/al/.local/lib/python2.7/site-packages/absl/flags/_flag.py", line 169, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --model_variant=resnet_v1_101_beta: value should be one of <xception_65|mobilenet_v2>
```
I changed model_variant to xception_65 and then got the following error:

 ```
Traceback (most recent call last):
  File "main.py", line 304, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 246, in main
    params=params)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2132, in __init__
    warm_start_from=warm_start_from)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 206, in __init__
    self._params = copy.deepcopy(params or {})
  File "/usr/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/usr/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/usr/lib/python2.7/copy_reg.py", line 94, in __newobj__
    return cls.__new__(cls, *args)
TypeError: __new__() takes at most 5 arguments (15 given)
```

I doubt that we weren't using the correct source code or path or augment because there are simply too many inconsistent definitions and function calls around. How am I supposed to make use of the command provided? 
Can somebody please give a bit guidance on how we could proceed?

**Comment by shizhiw** [comment]
What do you see in the code you run for [this](https://github.com/tensorflow/models/blob/master/research/deeplab/common.py#L48)? If it is the same as head, I expect not to see the first error. I'm suspecting that maybe the tensorflow/models/deeplab you are running is not recent?

**Comment by limslarmo** [comment]
> What do you see in the code you run for [this](https://github.com/tensorflow/models/blob/master/research/deeplab/common.py#L48)? If it is the same as head, I expect not to see the first error. I'm suspecting that maybe the tensorflow/models/deeplab you are running is not recent?
```
flags.DEFINE_enum('model_variant', 'mobilenet_v2',
                  ['xception_65', 'mobilenet_v2'], 'DeepLab model variant.')
```
Should I change this line to 
```flags.DEFINE_string('model_variant', 'mobilenet_v2', 'DeepLab model variant.')```?

**Comment by limslarmo** [comment]
I reinstalled tensorflow/models and this issue is gone, for future reference.
