### ISSUE TITLE
Deeplab: unable to eval model trained on TPU

### ISSUE THREAD

**Issue by ramesh8v** [tensorflow/tpu#314]
When I run eval mode, I'm getting this error: 

```
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

W0326 04:48:39.817662 140359414707648 __init__.py:44] file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
I0326 04:48:39.818242 140359414707648 discovery.py:272] URL being requested: GET https://www.googleapis.com/discovery/v1/apis/tpu/v1alpha1/rest
I0326 04:48:39.856997 140359414707648 discovery.py:873] URL being requested: GET https://tpu.googleapis.com/v1alpha1/projects/hopeful-keep-170717/locations/us-central1-a/nodes/rkramasamy?alt=json
I0326 04:48:39.857348 140359414707648 transport.py:157] Attempting refresh to obtain initial access_token
W0326 04:48:39.958188 140359414707648 __init__.py:44] file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
I0326 04:48:39.958589 140359414707648 discovery.py:272] URL being requested: GET https://www.googleapis.com/discovery/v1/apis/tpu/v1alpha1/rest
I0326 04:48:39.999516 140359414707648 discovery.py:873] URL being requested: GET https://tpu.googleapis.com/v1alpha1/projects/hopeful-keep-170717/locations/us-central1-a/nodes/rkramasamy?alt=json
I0326 04:48:39.999877 140359414707648 transport.py:157] Attempting refresh to obtain initial access_token
I0326 04:48:40.176651 140359414707648 estimator.py:201] Using config: {'_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
cluster_def {
  job {
name: "worker"
    tasks {
      key: 0
      value: "10.240.1.2:8470"
    }
  }
}
, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_train_distribute': None, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fa7db66c150>, '_model_dir': 'gs://ram8v_ckpt/exp/walnut_emprical', '_protocol': None, '_save_checkpoints_steps': 2000, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tpu_config': TPUConfig(iterations_per_loop=2000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=2, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None), '_tf_random_seed': None, '_save_summary_steps': 100, '_device_fn': None, '_cluster': <tensorflow.python.distribute.cluster_resolver.tpu_cluster_resolver.TPUClusterResolver object at 0x7fa7dc680f10>, '_experimental_distribute': None, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': None, '_evaluation_master': u'grpc://10.240.1.2:8470', '_eval_distribute': None, '_global_id_in_cluster': 0, '_master': u'grpc://10.240.1.2:8470'}
I0326 04:48:40.177443 140359414707648 tpu_context.py:202] _TPUContext: eval_on_tpu True
I0326 04:48:40.177989 140359414707648 evaluation.py:189] Waiting for new checkpoint at gs://ram8v_ckpt/exp/walnut_emprical
I0326 04:48:40.537626 140359414707648 evaluation.py:198] Found new checkpoint at gs://ram8v_ckpt/exp/walnut_emprical/model.ckpt-2000
I0326 04:48:40.538219 140359414707648 main.py:275] Starting to evaluate.
I0326 04:48:40.538842 140359414707648 tpu_system_metadata.py:59] Querying Tensorflow master (grpc://10.240.1.2:8470) for TPU system metadata.
2019-03-26 04:48:40.540458: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:354] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
I0326 04:48:40.554527 140359414707648 tpu_system_metadata.py:120] Found TPU system:
I0326 04:48:40.554785 140359414707648 tpu_system_metadata.py:121] *** Num TPU Cores: 8
I0326 04:48:40.555239 140359414707648 tpu_system_metadata.py:122] *** Num TPU Workers: 1
I0326 04:48:40.555358 140359414707648 tpu_system_metadata.py:124] *** Num TPU Cores Per Worker: 8
I0326 04:48:40.555517 140359414707648 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, -1, 10725014654337336124)
I0326 04:48:40.555824 140359414707648 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 12489304254504981064)
I0326 04:48:40.555937 140359414707648 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 17179869184, 790146627034714561)
I0326 04:48:40.556044 140359414707648 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 17179869184, 7551023334535984373)
I0326 04:48:40.556149 140359414707648 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 17179869184, 2451963462854478533)
I0326 04:48:40.556251 140359414707648 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 17179869184, 12698575579220148629)
I0326 04:48:40.556353 140359414707648 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 17179869184, 14098948770089202184)
I0326 04:48:40.556485 140359414707648 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 17179869184, 10388339330981323396)
I0326 04:48:40.556587 140359414707648 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 17179869184, 10610245514887821617)
I0326 04:48:40.556684 140359414707648 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 17179869184, 14220636923117948150)
I0326 04:48:40.556782 140359414707648 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 17179869184, 12174284822478410757)
W0326 04:48:40.625819 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
I0326 04:48:40.629319 140359414707648 estimator.py:1111] Calling model_fn.
W0326 04:48:40.678489 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/data/parallel_reader.py:242: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0326 04:48:40.685734 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py:278: input_producer (from tensorflow.python.training.input) is deprecated and will be remove
d in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0326 04:48:40.686182 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py:190: limit_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
W0326 04:48:40.689793 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py:113: count_up_to (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Dataset.range instead.
W0326 04:48:40.690021 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py:2132: count_up_to (from tensorflow.python.ops.state_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Dataset.range instead.
W0326 04:48:40.693058 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py:199: __init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W0326 04:48:40.694391 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py:199: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W0326 04:48:40.695091 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py:202: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
W0326 04:48:40.703145 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/data/parallel_reader.py:94: __init__ (from tensorflow.python.ops.io_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TFRecordDataset`.
W0326 04:48:41.100467 140359414707648 deprecation.py:323] From /home/rkramasamy/tpu/models/experimental/deeplab/data_pipeline.py:152: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
W0326 04:48:41.123173 140359414707648 tpu_estimator.py:1303] Input pipeline contains one or more QueueRunners. It could be slow and not scalable. Please consider converting your input pipeline to use `tf.data` instead (see https://www.tensorflow.org/guide/datasets for instructions.
I0326 04:48:52.495244 140359414707648 model.py:252] No init checkpoint found. Training from scratch.
W0326 04:48:52.508285 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py:2655: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
W0326 04:48:53.587522 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/metrics_impl.py:259: to_int64 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
I0326 04:48:53.679085 140359414707648 estimator.py:1113] Done calling model_fn.
I0326 04:48:53.695089 140359414707648 evaluation.py:257] Starting evaluation at 2019-03-26T04:48:53Z
I0326 04:48:53.695481 140359414707648 tpu_estimator.py:447] TPU job name worker
I0326 04:48:55.270180 140359414707648 monitored_session.py:222] Graph was finalized.
W0326 04:48:55.271234 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
I0326 04:48:55.324706 140359414707648 saver.py:1270] Restoring parameters from gs://ram8v_ckpt/exp/walnut_emprical/model.ckpt-2000
I0326 04:49:00.459814 140359414707648 session_manager.py:491] Running local_init_op.
I0326 04:49:00.943324 140359414707648 session_manager.py:493] Done running local_init_op.
W0326 04:49:01.748936 140359414707648 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py:809: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
I0326 04:49:06.894069 140359414707648 tpu_estimator.py:504] Init TPU system
I0326 04:49:13.632316 140359414707648 tpu_estimator.py:510] Initialized TPU in 6 seconds
I0326 04:49:13.633603 140357694113536 tpu_estimator.py:463] Starting infeed thread controller.
I0326 04:49:13.634270 140359414707648 util.py:51] Initialized dataset iterators in 0 seconds
I0326 04:49:13.634533 140358247769856 tpu_estimator.py:482] Starting outfeed thread controller.
I0326 04:49:14.131616 140359414707648 tpu_estimator.py:536] Enqueue next (181) batch(es) of data to infeed.
I0326 04:49:14.132359 140359414707648 tpu_estimator.py:540] Dequeue next (181) batch(es) of data from outfeed.
I0326 04:49:19.272789 140357694113536 error_handling.py:70] Error recorded from infeed: PaddingFIFOQueue '_31_input_pipeline_task0/batch/padding_fifo_queue' is closed and has insufficient elements (requested 8, current size 0)
         [[node input_pipeline_task0/batch (defined at /home/rkramasamy/tpu/models/experimental/deeplab/data_pipeline.py:152) ]]

Caused by op u'input_pipeline_task0/batch', defined at:
  File "/home/rkramasamy/tpu/models/experimental/deeplab/main.py", line 303, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/rkramasamy/tpu/models/experimental/deeplab/main.py", line 279, in main
    steps=eval_dataset.num_samples // FLAGS.eval_batch_size
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2473, in evaluate
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 469, in evaluate
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 511, in _actual_eval
    return _evaluate()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 493, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1424, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1460, in _call_model_fn_eval
    features, labels, model_fn_lib.ModeKeys.EVAL, config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2251, in _call_model_fn
    config)
File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1112, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2547, in _model_fn
    input_holders.generate_infeed_enqueue_ops_and_dequeue_fn())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1167, in generate_infeed_enqueue_ops_and_dequeue_fn
    self._invoke_input_fn_and_record_structure())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1249, in _invoke_input_fn_and_record_structure
    host_device, host_id))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 756, in generate_per_host_enqueue_ops_fn_for_host
    inputs = _Inputs.from_input_fn(input_fn(user_context))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2423, in _input_fn
    return input_fn(**kwargs)
  File "/home/rkramasamy/tpu/models/experimental/deeplab/data_pipeline.py", line 152, in __call__
    dynamic_pad=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 1019, in batch
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 789, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 488, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3645, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): PaddingFIFOQueue '_31_input_pipeline_task0/batch/padding_fifo_queue' is closed and has insufficient elements (requested 8, current size 0)
         [[node input_pipeline_task0/batch (defined at /home/rkramasamy/tpu/models/experimental/deeplab/data_pipeline.py:152) ]]

I0326 04:49:29.684340 140359414707648 monitored_session.py:1180] An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. This error may also occur due to a gRPC failure caused by high memory or network bandwidth usage in the parameter servers. If this error occurs repeatedly, try increasing the number of parameter servers assigned to the job. Error: Socket closed
I0326 04:49:29.685391 140358247769856 error_handling.py:70] Error recorded from outfeed: Step was cancelled by an explicit call to `Session::Close()`.
I0326 04:49:29.687127 140359414707648 monitored_session.py:222] Graph was finalized.
I0326 04:49:29.745423 140359414707648 saver.py:1270] Restoring parameters from gs://ram8v_ckpt/exp/walnut_emprical/model.ckpt-2000
I0326 04:49:47.553760 140359414707648 session_manager.py:491] Running local_init_op.
I0326 04:49:47.927251 140359414707648 session_manager.py:493] Done running local_init_op.
I0326 04:49:52.005162 140359414707648 tpu_estimator.py:504] Init TPU system
I0326 04:49:58.016350 140359414707648 tpu_estimator.py:510] Initialized TPU in 6 seconds
I0326 04:49:58.017349 140358222591744 tpu_estimator.py:463] Starting infeed thread controller.
I0326 04:49:58.018022 140359414707648 util.py:51] Initialized dataset iterators in 0 seconds
I0326 04:49:58.018142 140358480029440 tpu_estimator.py:482] Starting outfeed thread controller.
I0326 04:49:58.947154 140359414707648 tpu_estimator.py:536] Enqueue next (181) batch(es) of data to infeed.
I0326 04:49:58.947523 140359414707648 tpu_estimator.py:540] Dequeue next (181) batch(es) of data from outfeed.
I0326 04:50:04.133166 140358222591744 error_handling.py:70] Error recorded from infeed: PaddingFIFOQueue '_7_input_pipeline_task0/batch/padding_fifo_queue' is closed and has insufficient elements (requested 8, current size 0)
         [[node input_pipeline_task0/batch (defined at /home/rkramasamy/tpu/models/experimental/deeplab/data_pipeline.py:152) ]]

Caused by op u'input_pipeline_task0/batch', defined at:
  File "/home/rkramasamy/tpu/models/experimental/deeplab/main.py", line 303, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/rkramasamy/tpu/models/experimental/deeplab/main.py", line 279, in main
    steps=eval_dataset.num_samples // FLAGS.eval_batch_size
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2473, in evaluate
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 469, in evaluate
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 511, in _actual_eval
    return _evaluate()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 493, in _evaluate
    self._evaluate_build_graph(input_fn, hooks, checkpoint_path))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1424, in _evaluate_build_graph
    self._call_model_fn_eval(input_fn, self.config))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1460, in _call_model_fn_eval
    features, labels, model_fn_lib.ModeKeys.EVAL, config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2251, in _call_model_fn
    config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1112, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2547, in _model_fn
    input_holders.generate_infeed_enqueue_ops_and_dequeue_fn())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1167, in generate_infeed_enqueue_ops_and_dequeue_fn
    self._invoke_input_fn_and_record_structure())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1249, in _invoke_input_fn_and_record_structure
    host_device, host_id))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 756, in generate_per_host_enqueue_ops_fn_for_host
    inputs = _Inputs.from_input_fn(input_fn(user_context))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2423, in _input_fn
    return input_fn(**kwargs)
  File "/home/rkramasamy/tpu/models/experimental/deeplab/data_pipeline.py", line 152, in __call__
    dynamic_pad=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 1019, in batch
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 789, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 488, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 3645, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): PaddingFIFOQueue '_7_input_pipeline_task0/batch/padding_fifo_queue' is closed and has insufficient elements (requested 8, current size 0)
         [[node input_pipeline_task0/batch (defined at /home/rkramasamy/tpu/models/experimental/deeplab/data_pipeline.py:152) ]]

```
I'd apprecaite any help to resolve this.

**Comment by saberkun** [comment]
It seems your eval data is out-of-range. Can you double check the number of eval steps for eval input fn?

**Comment by ramesh8v** [comment]
Thanks, @saberkun. Changing eval steps, or batch size doesn't seem to help. My input looks like this:
```
python ./tpu/models/experimental/deeplab/main.py \
--mode='eval' \
--num_shards=8 \
--alsologtostderr=true \
--model_dir=${MODEL_DIR} \
--dataset_dir=${DATASET_DIR} \
--init_checkpoint=${INIT_CHECKPOINT} \
--train_split="train" \
--eval_split="val" \
--train_steps=5000 \
--steps_per_eval=1000 \  ### I played around with this value
--train_batch_size=64 \
--eval_batch_size=16 \  ### I played around with this value
--model_variant=xception_65 \
--image_pyramid=1. \
--aspp_with_separable_conv=false \
--multi_grid=1 \
--multi_grid=2 \
--multi_grid=4 \
--decoder_use_separable_conv=false \
--use_tpu=True
```

**Comment by borosdenes** [comment]
Are you sure that the `dataset_dir` is set up properly, that it is poining at the required bucked, without any typo? I've ran into somewhat similar error message, when I mistyped the the path to the dataset.

**Comment by ramesh8v** [comment]
Thanks, @borosdenes. I used the same script to train the model, I just changed `mode='train' `to `mode='eval'` for evaluation.

**Comment by borosdenes** [comment]
Well then I believe the following could happen:
 - no files match the file pattern according to `eval_split` flag (not sure of this particular example, I was using `resnet_main.py` with custom data),
 - `num_samples` from `eval_dataset` is incorrect. Therefore you try to iterate through more data than what is accessible.

To give more traceable insights for others about your issue, (1) you could try using mode `train_and_eval` and see when your error is raised. (2) Moreover does the issue happen right after calling `estimator.evaluate` (sign of completely missing data), or does that happen after the evaluation has been running for a while (sign of trying to iterate through more data than what is accessible)?

Not sure if all this helps, let's also wait for replies from others.

**Comment by ramesh8v** [comment]
Increasing the number of samples for eval solved the issue.
