### ISSUE TITLE
application_model.py with TPU doesn't work because of the lack of initialize_tpu_system

### ISSUE THREAD

**Issue by yu-iskw** [tensorflow/tpu#316]
## Error Message
When I tried to run `tpu/models/experimental/keras_application/application_model.py`, I got the error. It seems that even tensorflow 1.13.1 doesn't have `initialize_tpu_system`.

```
Traceback (most recent call last):
  File "title_gen/train/keras_application.py", line 168, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "tpu/models/experimental/keras_application/application_model.py", line 164, in main
    run()
  File "tpu/models/experimental/keras_application/application_model.py", line 134, in run
    tf.contrib.distribute.initialize_tpu_system(resolver)
AttributeError: 'module' object has no attribute 'initialize_tpu_system'
```

## Environment
- Python: 2.7
- Tensorflow: 1.13.1
- TPU
  - TF Version: 1.13
  - Version: v2-8

**Comment by saberkun** [comment]
tf.contrib.distribute is very new and 1.13 release is actually 1 month behind. I am wondering if you only can have it in tf-nightly. Also in TF 2.0 preview, the contrib is gone, so it becomes tf.distribute.initialize_tpu_system.
Thanks

**Comment by saberkun** [comment]
You may also try: tf.tpu.experimental.initialize_tpu_system()
if it is still not there, the functionality will need to wait 1.14 release.
