### ISSUE TITLE
Running Retrained EfficientNet

### ISSUE THREAD

**Issue by erinkmcd** [tensorflow/tpu#439]
Tensorflow version: 1.13.1 
Specs: Ubuntu 16.04 w/ 2 TeslaM60 GPUs

I am training an efficient net model on my own dataset mostly following the tutorial but modifying as necessary for gpu.

I trained with the following command: 
` python3 main.py --use_tpu=False --data_dir=/home/ubuntu/records --data_format=channels_first --transpose_input=False `

I moved a checkpoint from a specific step to a separate directory and created the following checkpoint file:
` model_checkpoint_path: "/home/ubuntu/191403/model.ckpt-191403"
all_model_checkpoint_paths: "/home/ubuntu/191403/model.ckpt-191403" `

When I run:
` python3 eval_ckpt_main.py --model_name=efficientnet-b0 --ckpt_dir=/home/ubuntu/191403 --example_img=/home/ubuntu/example.jpg --labels_map_file=/home/ubuntu/labels_map.txt --num_images=1 `
(Note: before running eval ckpt I forced to use cpu by setting CUDA_VISIBLE_DEVICES to -1 because gpu is still being used to continue training)

I get the following error:
```W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at conv_ops.cc:437 : Invalid argument: input depth must be evenly divisible by filter depth: 320 vs 7
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: input depth must be evenly divisible by filter depth: 320 vs 7
	 [[{{node efficientnet-b0/model/head/conv2d/Conv2D}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval_ckpt_main.py", line 236, in <module>
    app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 274, in run
    _run_main(main, argv)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "eval_ckpt_main.py", line 226, in main
    FLAGS.labels_map_file)
  File "eval_ckpt_main.py", line 173, in eval_example_images
    ckpt_dir, image_files, [0] * len(image_files))
  File "eval_ckpt_main.py", line 148, in run_inference
    out_probs = sess.run(probs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: input depth must be evenly divisible by filter depth: 320 vs 7
	 [[node efficientnet-b0/model/head/conv2d/Conv2D (defined at /usr/local/lib/python3.5/dist-packages/tensorflow/tpu/models/official/efficientnet/efficientnet_model.py:431) ]]

Caused by op 'efficientnet-b0/model/head/conv2d/Conv2D', defined at:
  File "eval_ckpt_main.py", line 236, in <module>
    app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 274, in run
    _run_main(main, argv)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "eval_ckpt_main.py", line 226, in main
    FLAGS.labels_map_file)
  File "eval_ckpt_main.py", line 173, in eval_example_images
    ckpt_dir, image_files, [0] * len(image_files))
  File "eval_ckpt_main.py", line 141, in run_inference
    probs = self.build_model(images, is_training=False)
  File "eval_ckpt_main.py", line 112, in build_model
    features, self.model_name, is_training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/tpu/models/official/efficientnet/efficientnet_builder.py", line 201, in build_model
    logits = model(images, training=training)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/tpu/models/official/efficientnet/efficientnet_model.py", line 431, in call
    self._bn1(self._conv_head(outputs), training=training))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/base.py", line 530, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/layers/convolutional.py", line 194, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 966, in __call__
    return self.conv_op(inp, filter)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 591, in __call__
    return self.call(inp, filter)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/nn_ops.py", line 208, in __call__
    name=self.name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 1026, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): input depth must be evenly divisible by filter depth: 320 vs 7
	 [[node efficientnet-b0/model/head/conv2d/Conv2D (defined at /usr/local/lib/python3.5/dist-packages/tensorflow/tpu/models/official/efficientnet/efficientnet_model.py:431) ]]
```

I cannot find anyone with specifically the same error but I have a hunch that the issue is that while the model was trained with channels_first to work on gpu, the data may be passed channels_last. Although data_format is a flag option for training, it does not seem to be an option for evaluation and I do not know how to modify that OR if that is even the underlying issue. Please let me know if there's any other info I can provide, thanks!

**Comment by saberkun** [comment]
channels_first flag did a transpose inside the model function.
if the model is trained will channels_first, eval will also do the transpose.

**Comment by erinkmcd** [comment]
Hi saberkun, thanks for the quick response. I followed your suggestion and add a data_format flag that when set to channels first will transpose the data. I re-ran eval_ckpt_main with those change and got a very similar error, just with different values. Is this a separate issue, or did I make a mistake in the transpose? (I based my changes on how main.py does it [here](https://github.com/tensorflow/tpu/blob/master/models/official/efficientnet/main.py#L268) )

New error:
`InvalidArgumentError (see above for traceback): input depth must be evenly divisible by filter depth: 224 vs 3
	 [[node efficientnet-b0/model/stem/conv2d/Conv2D (defined at /usr/local/lib/python3.5/dist-packages/tensorflow/tpu/models/official/efficientnet/efficientnet_model.py:397) ]]`
(224 vs 3 as opposed to 320 vs 7 in the original error)

Modified build_model:
```
 def build_model(self, features, is_training):
    """Build model with input features."""
    if FLAGS.data_format == 'channels_first':
      features = tf.transpose(features, [0, 3, 1, 2])
      stats_shape = [3,1,1]
    else:
      stats_shape=[1,1,3]

    features -= tf.constant(MEAN_RGB, shape=stats_shape, dtype=features.dtype)
    features /= tf.constant(STDDEV_RGB, shape=stats_shape, dtype=features.dtype)

    logits, _ = efficientnet_builder.build_model(
        features, self.model_name, is_training)
    probs = tf.nn.softmax(logits)
    probs = tf.squeeze(probs)
    return probs
```

**Comment by saberkun** [comment]
What's the TF version you are using? NCHW must run on GPU. Does this indicate your eval do not run on GPU?

It probably is still some transpose mismatch error.

**Comment by erinkmcd** [comment]
I'm using tf version 1.13. You are correct, I tried to run GPU trained model on cpu with channels_first and that created the above error. Once I ran the eval on GPU with channels_first, I am getting a new error:
`
predicted class for image /home/ubuntu/example.jpg: 
Traceback (most recent call last):
  File "eval_ckpt_main.py", line 250, in <module>
    app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 274, in run
    _run_main(main, argv)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 238, in _run_main
    sys.exit(main(argv))
  File "eval_ckpt_main.py", line 240, in main
    FLAGS.labels_map_file)
  File "eval_ckpt_main.py", line 192, in eval_example_images
    j, pred_prob[i][j] * 100, classes[str(idx)]))
KeyError: '0'
`

My labels map file contains:
` {'1': 'class1', '2': 'class2'} ` which is based on my labels.pbtxt file from the training which has the same mapping. I did not use 0 in the mapping as my understanding is that 0 is reserved as a 'not' class when training. Does this imply that the example image does not belong strongly enough to either class 1 or class 2?

**Comment by erinkmcd** [comment]
Closing out because the first error is solved and the subsequent errors were user related.

If you're facing an issue relating to channels, use the most recent above snippet for build_model and pass a channels flag when running on gpu. (and ensure you're actually running both training and eval on gpu)

The later key error issues stemmed from user error, namely malformed training data. There was a discrepancy between the map in my labels_map.txt and the map I used when creating the tfrecords.

Thanks @saberkun for all the help! Would have taken me a while to find and modify the build_model function.

**Comment by VCBE123** [comment]
I meet the error when I load a .pb model.
```bash
  tf.import_graph_def(graph_def,name="")
  File "/data/lirui/anaconda3/envs/autosp/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/data/lirui/anaconda3/envs/autosp/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 422, in import_graph_def
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 352 and 9 for 'efficientnet-b2/model/head/conv2d/Conv2D' (op: 'Conv2D') with input shapes: [?,?,?,352], [1,1,9,1408].
```

The code to write .pb:
```python
def freeze_graph(image_size):
  with tf.Graph().as_default():
    input_tensor = tf.placeholder(shape=(None,image_size, image_size,3), dtype=tf.float32, name='input')
    logits,_=build_model(input_tensor,"efficientnet-b2",training=False)
    print(logits,"logist")
    tf.argmax(logits, axis=1, output_type=tf.int32,name="argmax")
    tf.nn.softmax(logits,axis=1,name="softmax")
    output_nodes_names = ['argmax',"softmax"]
    config = tf.ConfigProto(allow_soft_placement=True)
    sess = tf.Session(config=config)
    saver = tf.train.Saver()
    ckpt = tf.train.get_checkpoint_state(FLAGS.model_dir)
    saver.restore(sess, ckpt.model_checkpoint_path)
    output_graph_def = tf.graph_util.convert_variables_to_constants(
      sess=sess,
      input_graph_def=sess.graph_def,
      output_node_names=output_nodes_names
    )
    with tf.gfile.GFile(FLAGS.save_path, 'wb') as f:
         f.write(output_graph_def.SerializeToString())
```

I load the .pb:
```python
with tf.Session(config=config) as sess:
    with gfile.FastGFile(pb_file_path,'rb') as f:
        graph_def=tf.GraphDef()
        graph_def.ParseFromString(f.read())
        sess.graph.as_default()
        tf.import_graph_def(graph_def,name="")
        sess.run(tf.global_variables_initializer())
```
