### ISSUE TITLE
Got errors when I ran EfficientNet on Google cloud

### ISSUE THREAD

**Issue by fastalgo** [tensorflow/tpu#620]
ERROR:tensorflow:Error recorded from training_loop: 'Context' object has no attribute 'summary_recording_distribution_strategy'
E1203 23:23:14.209724 139643935446784 error_handling.py:75] Error recorded from training_loop: 'Context' object has no attribute 'summary_recording_distribution_strategy'
INFO:tensorflow:training_loop marked as finished
I1203 23:23:14.210070 139643935446784 error_handling.py:101] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W1203 23:23:14.210274 139643935446784 error_handling.py:135] Reraising captured error
Traceback (most recent call last):
  File "main.py", line 807, in <module>
    app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.5/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "main.py", line 779, in main
    est.train(input_fn=imagenet_train.input_fn, max_steps=next_checkpoint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3035, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 136, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 696, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3030, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1160, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1190, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2857, in _call_model_fn
    config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1148, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3159, in _model_fn
    _train_on_tpu_system(ctx, model_fn_wrapper, dequeue_fn))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3604, in _train_on_tpu_system
    device_assignment=ctx.device_assignment)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/tpu/tpu.py", line 1458, in split_compile_and_shard
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/tpu/tpu.py", line 1173, in split_compile_and_replicate
    outputs = computation(*computation_inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3585, in multi_tpu_train_steps_on_single_shard
    with tpu_context._TPUEstimatorReplicaContext(replica_id):  # pylint: disable=protected-access
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_context.py", line 805, in __enter__
    ctx.summary_recording_distribution_strategy)
AttributeError: 'Context' object has no attribute 'summary_recording_distribution_strategy'

**Comment by fastalgo** [comment]
The configurations of my platform:

  Name:                 v3-64-4tb
  Zone:                 europe-west4-a
  GCP Project:          cloud-tpu-colab-integration
  TensorFlow Version:   2.1
  VM:
      Machine Type:     n1-standard-2
      Disk Size:        4096 GB
      Preemptible:      false
  Cloud TPU:
      Size:             v3-64
      Preemptible:      true
      Reserved:         false
