### ISSUE TITLE
HbmAddress is expired.

### ISSUE THREAD

**Issue by bojone** [tensorflow/tpu#631]
I ran a keras model on tpu-v3 and it errors:

> Traceback (most recent call last):
>   File "pretraining.py", line 173, in <module>
>     callbacks=[checkpoint, csv_logger],
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training.py", line 727, in fit
>     use_multiprocessing=use_multiprocessing)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training_distributed.py", line 670, in fit
>     validation_freq=validation_freq)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training_distributed.py", line 243, in experimental_tpu_fit_loop
>     _, outputs = K.batch_get_value([train_op, output_tensors])
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/backend.py", line 3185, in batch_get_value
>     return get_session(tensors).run(tensors)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
>     feed_dict_tensor, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
>     run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.FailedPreconditionError: From /job:worker/replica:0/task:0:
> HbmAddress is expired.
>          [[node TPUReplicateMetadata (defined at /usr/local/lib/python2.7/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
> 
> Original stack trace for u'TPUReplicateMetadata':
>   File "pretraining.py", line 173, in <module>
>     callbacks=[checkpoint, csv_logger],
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training.py", line 727, in fit
>     use_multiprocessing=use_multiprocessing)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training_distributed.py", line 670, in fit
>     validation_freq=validation_freq)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/training_distributed.py", line 196, in experimental_tpu_fit_loop
>     initial_loop_values=initial_loop_values)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1756, in experimental_run_steps_on_iterator
>     initial_loop_values)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/distribute/tpu_strategy.py", line 334, in _experimental_run_steps_on_iterator
>     replicate_outputs = rewrite_fn()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/distribute/tpu_strategy.py", line 315, in rewrite_fn
>     run_fn, replicate_inputs, device_assignment=self._device_assignment)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tpu/tpu.py", line 639, in replicate
>     maximum_shapes=maximum_shapes)[1]
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tpu/tpu.py", line 927, in split_compile_and_replicate
>     num_replicas=num_replicas, use_tpu=use_tpu, **metadata_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/ops/gen_tpu_ops.py", line 6105, in tpu_replicate_metadata
>     name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
>     op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
>     attrs, op_def, compute_device)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
>     op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
>     self._traceback = tf_stack.extract_stack()

This error has beed reproduced many times. Once it occurs at the beginning of training. And once it occurs after 300k steps of training iteration. And I can not find any description of it.

**Comment by Sebastian-Koenig** [comment]
`Exception ignored in: <bound method IteratorResourceDeleter.__del__ of <tensorflow.python.data.ops.iterator_ops.IteratorResourceDeleter object at 0x7f7b9c19bac8>>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/data/ops/iterator_ops.py", line 537, in __del__
    handle=self._handle, deleter=self._deleter)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 1148, in delete_iterator
    _ops.raise_from_not_ok_status(e, name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.FailedPreconditionError: HbmAddress is expired. [Op:DeleteIterator]`

Encountering a similar issue with the HbmAddress when trying to compile a NASNetLarge on a TPU.

**Comment by volody** [comment]
It could be problem with optimizer created outside of strategy.scope
