### ISSUE TITLE
Run-time shape mismatch for TPUExecute argument error when using TPU and SeparableConv2D

### ISSUE THREAD

**Issue by ksasi** [tensorflow/tpu#632]
Hi,

We are receiving the following error message when using TPU in Colab with Tensorflow 2.0. The CNN is built using SeparableConv2D.

Epoch 1/50
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

10 frames
InvalidArgumentError: From /job:worker/replica:0/task:0:
Run-time shape mismatch for TPUExecute argument[0] (cond_31/output/_726). Expected element_type: F32
dimensions: 16
dimensions: 32
dimensions: 32
dimensions: 3
layout {
  minor_to_major: 2
  minor_to_major: 1
  minor_to_major: 3
  minor_to_major: 0
  format: DENSE
}
is_dynamic_dimension: false
is_dynamic_dimension: false
is_dynamic_dimension: false
is_dynamic_dimension: false
; got element_type: F32
dimensions: 13
dimensions: 32
dimensions: 32
dimensions: 3
layout {
  minor_to_major: 2
  minor_to_major: 1
  minor_to_major: 3
  minor_to_major: 0
  format: DENSE
}
is_dynamic_dimension: false
is_dynamic_dimension: false
is_dynamic_dimension: false
is_dynamic_dimension: false

	 [[{{node TPUReplicateMetadata_1}}]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1382                     '\nsession_config.graph_options.rewrite_options.'
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 
   1386   def _extend_graph(self):

InvalidArgumentError: From /job:worker/replica:0/task:0:
Run-time shape mismatch for TPUExecute argument[0] (cond_31/output/_726). Expected element_type: F32
dimensions: 16
dimensions: 32
dimensions: 32
dimensions: 3
layout {
  minor_to_major: 2
  minor_to_major: 1
  minor_to_major: 3
  minor_to_major: 0
  format: DENSE
}
is_dynamic_dimension: false
is_dynamic_dimension: false
is_dynamic_dimension: false
is_dynamic_dimension: false
; got element_type: F32
dimensions: 13
dimensions: 32
dimensions: 32
dimensions: 3
layout {
  minor_to_major: 2
  minor_to_major: 1
  minor_to_major: 3
  minor_to_major: 0
  format: DENSE
}
is_dynamic_dimension: false
is_dynamic_dimension: false
is_dynamic_dimension: false
is_dynamic_dimension: false

	 [[node TPUReplicateMetadata_1 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1751) ]]

Original stack trace for 'TPUReplicateMetadata_1':
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-ff2bad83eaa8>", line 5, in <module>
    validation_data = (test_features.astype(np.float32), test_labels.astype(np.float32)), verbose=1)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_distributed.py", line 670, in fit
    validation_freq=validation_freq)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_distributed.py", line 196, in experimental_tpu_fit_loop
    initial_loop_values=initial_loop_values)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/distribute_lib.py", line 1733, in experimental_run_steps_on_iterator
    initial_loop_values)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/tpu_strategy.py", line 334, in _experimental_run_steps_on_iterator
    replicate_outputs = rewrite_fn()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/distribute/tpu_strategy.py", line 315, in rewrite_fn
    run_fn, replicate_inputs, device_assignment=self._device_assignment)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/tpu/tpu.py", line 637, in replicate
    maximum_shapes=maximum_shapes)[1]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/tpu/tpu.py", line 909, in split_compile_and_replicate
    num_replicas=num_replicas, use_tpu=use_tpu, **metadata_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_tpu_ops.py", line 6108, in tpu_replicate_metadata
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3360, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1751, in __init__
    self._traceback = tf_stack.extract_stack()

Code to Reproduce the Issue :

https://gist.github.com/ksasi/9d2f3c713c3d0d25f94ea14a281b8936

Please advise.

**Comment by olehofman** [comment]
Already resolved? I am experiencing the same error on Google Colab, help very much appreciated!

**Comment by danyaljj** [comment]
This might be useful: 
https://stackoverflow.com/questions/51047070/tensorflow-i-got-a-shape-mismatch-in-execution-time
