### ISSUE TITLE
ModuleNotFoundError: No module named 'hyperparameters'

### ISSUE THREAD

**Issue by SharifElfouly** [tensorflow/tpu#790]
When I try to run a simple inference with `python3 ~/tpu/models/official/detection/main.py` I get the following error:

```
Traceback (most recent call last):
  File "/home/sharif/tpu/models/official/detection/inference.py", line 38, in <module>
    from configs import factory as config_factory
  File "/home/sharif/tpu/models/official/detection/configs/factory.py", line 17, in <module>
    from configs import classification_config
  File "/home/sharif/tpu/models/official/detection/configs/classification_config.py", line 18, in <module>
    from hyperparameters import params_dict
ModuleNotFoundError: No module named 'hyperparameters'
```

**Comment by abhi-kumar** [comment]
From the terminal where you are running the main.py code run this before it. (Basically adding models directory to python path)

```
export PYTHONPATH=$PYTHONPATH:~/tpu/models/
```

**Comment by gireek** [comment]
hi @abhi-kumar @SharifElfouly did you solve this? I am facing the same kind of error while running the fashionpedia project on colab. [This ](https://github.com/gireek/colab_fashionpedia/blob/master/tf_fashionpedia.ipynb)is my notebook.

**Comment by tnfru** [comment]
> From the terminal where you are running the main.py code run this before it. (Basically adding models directory to python path)
> 
> ```
> export PYTHONPATH=$PYTHONPATH:~/tpu/models/
> ```

This doesn't work for me either. Then it comes with utils.
