### ISSUE TITLE
Model inference failed with SpineNet-190 Mask-RCNN ckpt : Windows fatal exception and TypeErrors

### ISSUE THREAD

**Issue by lisqzqng** [tensorflow/tpu#792]
Hi,

I'm following the instructions in [GETTING_STARTED.md](https://github.com/tensorflow/tpu/blob/master/models/official/detection/GETTING_STARTED.md) to run inference on gpu, using   **win10 + tensorflow-gpu.2.2.0 + cuda 10.0 + python 3.6**

When I take the pretrained spinenet190 mask_rcnn checkpoint (updated in [Issue#781](https://github.com/tensorflow/tpu/issues/781)) to get predictions:  
```
(C:\Anaconda3) D:\Diwei\Spinenet\tpu-master>python D:\Diwei\Spinenet\tpu-master\models\official\detection\inference.py ^
Plus ? --model="mask_rcnn" ^
Plus ? --checkpoint_path="D:\Diwei\data\spinenet-190\model.ckpt-187600" ^
Plus ? --config_file="D:\Diwei\Spinenet\tpu-master\models\official\detection\configs\spinenet\spinenet190_mrcnn.yaml" ^
Plus ? --label_map_file="D:\Diwei\Spinenet\tpu-master\models\official\detection\datasets\coco_label_map.csv" ^
Plus ? --image_file_pattern="D:\Diwei\data\Kitano_Street_Kobe.jpg" ^
Plus ? --output_html="D:\Diwei\data\test_results"
```
Serveral errors occurred. The first says **Windows fatal exception: code 0xe06d7363** and is associated with the image processing **input_utils.resize_and_crop_image(...)** in [inference.py](https://github.com/tensorflow/tpu/blob/master/models/official/detection/inference.py): 
```
Windows fatal exception: code 0xe06d7363

Current thread 0x00000854 (most recent call first):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2328 in get_attr
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1859 in colocation_groups
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3415 in _create_op_helper
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3328 in _create_op_internal
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 744 in _apply_op_helper
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3901 in identity
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 282 in identity
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py", line 180 in wrapper
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 194 in _Identity
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2846 in with_dependencies
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\image_ops_impl.py", line 937 in pad_to_bounding_box
  File "D:\Diwei\Spinenet\tpu-master\models\official\detection\utils\input_utils.py", line 211 in resize_and_crop_image
  File "D:\Diwei\Spinenet\tpu-master\models\official\detection\inference.py", line 131 in main
  File "C:\Anaconda3\lib\site-packages\absl\app.py", line 251 in _run_main
  File "C:\Anaconda3\lib\site-packages\absl\app.py", line 300 in run
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40 in run
  File "D:\Diwei\Spinenet\tpu-master\models\official\detection\inference.py", line 222 in <module>
```
Then the following two **TypeErrors** occurred with the **model.build_outputs(...)** in [inference.py](https://github.com/tensorflow/tpu/blob/master/models/official/detection/inference.py): 
```
W0624 10:11:57.711931  2132 deprecation.py:323] From D:\Diwei\Spinenet\tpu-master\models\official\detection\modeling\architecture\nn_ops.py:387: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 543, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 543, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\compat.py", line 87, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got <bound method Layer.__call__ of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000025F7B55D320>>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Diwei\Spinenet\tpu-master\models\official\detection\inference.py", line 222, in <module>
    tf.app.run(main)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "C:\Anaconda3\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "D:\Diwei\Spinenet\tpu-master\models\official\detection\inference.py", line 140, in main
    images, {'image_info': images_info}, mode=mode_keys.PREDICT)
  File "D:\Diwei\Spinenet\tpu-master\models\official\detection\modeling\base_model.py", line 204, in build_outputs
    outputs = self._build_outputs(images, labels, mode)
  File "D:\Diwei\Spinenet\tpu-master\models\official\detection\modeling\maskrcnn_model.py", line 90, in _build_outputs
    backbone_features = self._backbone_fn(images, is_training)
  File "D:\Diwei\Spinenet\tpu-master\models\official\detection\modeling\architecture\spinenet.py", line 506, in __call__
    feats = self._build_stem_network(images, is_training)
  File "D:\Diwei\Spinenet\tpu-master\models\official\detection\modeling\architecture\spinenet.py", line 338, in _build_stem_network
    net = tf.identity(net, 'initial_conv')
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 282, in identity
    ret = gen_array_ops.identity(input, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3901, in identity
    "Identity", input=input, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 473, in _apply_op_helper
    raise err
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 470, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1341, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 321, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 262, in constant
    allow_broadcast=True)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\constant_op.py", line 300, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 547, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'method'> to Tensor. Contents: <bound method Layer.__call__ of <tensorflow.python.layers.convolutional.Conv2D object at 0x0000025F7B55D320>>. Consider casting elements to a supported type.
```
Not sure how to fix them ...

**Comment by lisqzqng** [comment]
Problem partially caused by tensorflow version. When changed back to tensorflow-gpu 1.15.0, the windows fatal error solved
