### ISSUE TITLE
resnet_main: use_tpu=False fails on eval

### ISSUE THREAD

**Issue by karandwivedi42** [tensorflow/tpu#80]
When testing with `use_tpu=False` and `data_format=channels_first` on a device with GPU, I face an error:

```
Traceback (most recent call last):
  File "tinyin_main.py", line 428, in <module>
    tf.app.run()
  File "/home/karan/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "tinyin_main.py", line 414, in main
    steps=NUM_EVAL_IMAGES // FLAGS.eval_batch_size)
  File "/home/karan/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 416, in evaluate
    name=name)
  File "/home/karan/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 930, in _evaluate_model
    features, labels, model_fn_lib.ModeKeys.EVAL, self.config)
  File "/home/karan/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/estimator/estimator.py", line 804, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/karan/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1810, in _model_fn
    return model_fn_wrapper.call_without_tpu(features, labels)
  File "/home/karan/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1040, in call_without_tpu
    return self._call_model_fn(features, labels)
  File "/home/karan/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1229, in _call_model_fn
    estimator_spec = self._model_fn(features=features, **kwargs)
  File "tinyin_main.py", line 203, in resnet_model_fn
    inputs=features, is_training=(mode == tf.estimator.ModeKeys.TRAIN))
  File "/home/karan/metalearning-project/tpu/models/official/resnet/tinyin_model.py", line 277, in model
    data_format=data_format)
  File "/home/karan/metalearning-project/tpu/models/official/resnet/tinyin_model.py", line 127, in conv2d_fixed_padding
    data_format=data_format)
  File "/home/karan/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py", line 619, in conv2d
    return layer.apply(inputs)
  File "/home/karan/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 815, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/karan/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 688, in __call__
    self.build(input_shapes)
  File "/home/karan/anaconda2/envs/tf/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py", line 133, in build
    raise ValueError('The channel dimension of the inputs '
ValueError: The channel dimension of the inputs should be defined. Found `None`.
```

**Comment by karandwivedi42** [comment]
Solved for me by following this: https://stackoverflow.com/a/48618066
