### ISSUE TITLE
How to train EfficientNet on GPU and convert to tflite for edgeTPU?

### ISSUE THREAD

**Issue by alan303138** [tensorflow/tpu#850]
How to train EfficientNet on GPU with my own data and convert to tflite for edgeTPU?
I saw 
EfficientNet-EdgeTPU-S
EfficientNet-EdgeTPU-M
EfficientNet-EdgeTPU-L.
But dont know how to retrain them.

**Comment by rklaic** [comment]
I have the same problem training the edgeTPU models for ussing them on my coral. For the moment I use **model_maker**  https://github.com/tensorflow/examples/tree/master/tensorflow_examples/lite/model_maker  to train a new efficientnet lite model in my PC GPU and use that model for inference. I couldn't find any documentation of how to train "efficientnet-edgetpu-S" without having to use google cloud TPU service. Maybe playing with the **main.py** script, ussing"--use_tpu=false" and changind the data/models directories?  I havent looked the code in detail.

**Comment by alan303138** [comment]
`python main.py  --data_dir ./data/tf_records/train --num_label_classes=3 --model_dir=efficientnet-edgetpu-S --model_name=efficientnet-edgetpu-S  --use_tpu=false `

[tf.config.experimental.VirtualDeviceConfiguration(memory_limit=6144)])`
> INFO:tensorflow:Saving checkpoints for 106000 into efficientnet-edgetpu-S\model.ckpt.
I1205 19:46:44.063242  7464 basic_session_run_hooks.py:618] Saving checkpoints for 106000 into efficientnet-edgetpu-S\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 106000...
I1205 19:46:45.400545  7464 basic_session_run_hooks.py:626] Calling checkpoint listeners after saving checkpoint 106000...
2020-12-05 19:46:45.573997: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2020-12-05 19:46:47.472666: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-12-05 19:46:48.113473: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-12-05 19:46:48.586368: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-12-05 19:46:49.364750: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-12-05 19:46:49.364866: E tensorflow/stream_executor/cuda/cuda_dnn.cc:340] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
2020-12-05 19:46:49.368766: E tensorflow/stream_executor/cuda/cuda_dnn.cc:336] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2020-12-05 19:46:49.368837: E tensorflow/stream_executor/cuda/cuda_dnn.cc:340] Error retrieving driver version: Unimplemented: kernel reported driver version not implemented on Windows
INFO:tensorflow:training_loop marked as finished
I1205 19:46:49.544490  7464 error_handling.py:115] training_loop marked as finished
WARNING:tensorflow:Reraising captured error
W1205 19:46:49.546491  7464 error_handling.py:149] Reraising captured error
Traceback (most recent call last):
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node efficientnet-edgetpu-S/model/stem/conv2d/Conv2D}}]]
         [[add/_3983]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node efficientnet-edgetpu-S/model/stem/conv2d/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 862, in <module>
    app.run(main)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "main.py", line 822, in main
    hooks=hooks)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 3089, in train
    rendezvous.raise_errors()
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\tpu\error_handling.py", line 150, in raise_errors
    six.reraise(typ, value, traceback)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 3084, in train
    saving_listeners=saving_listeners)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1208, in _train_model_default
    saving_listeners)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1511, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 778, in run
    run_metadata=run_metadata)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1283, in run
    run_metadata=run_metadata)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1384, in run
    raise six.reraise(*original_exc_info)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1369, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1442, in run
    run_metadata=run_metadata)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\monitored_session.py", line 1200, in run
    return self._sess.run(*args, **kwargs)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    run_metadata_ptr)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1369, in _do_run
    run_metadata)
  File "C:\Users\alan\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node efficientnet-edgetpu-S/model/stem/conv2d/Conv2D (defined at O:\tpu\models\official\efficientnet\utils.py:258) ]]
         [[add/_3983]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node efficientnet-edgetpu-S/model/stem/conv2d/Conv2D (defined at O:\tpu\models\official\efficientnet\utils.py:258) ]]
0 successful operations.
0 derived errors ignored.
