### ISSUE TITLE
Efficientnet Lite - ValueError: Can't load save_path when it is None.

### ISSUE THREAD

**Issue by BaderTim** [tensorflow/tpu#902]
### Description
I'm trying to load a checkpoint of the `efficientnet-lite1` model, but I'm running into the same error over and over again.  
With the same setup `efficientnet-b3` works without any issues.  

### Preparation
```
$ wget https://upload.wikimedia.org/wikipedia/commons/f/fe/Giant_Panda_in_Beijing_Zoo_1.JPG -O panda.jpg'
  
model_name = 'efficientnet-lite1' #@param
  
$ wget https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/ckpts/{model_name}.tar.gz -O {model_name}.tar.gz
$ tar xf {model_name}.tar.gz
$ wget https://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/eval_data/labels_map.txt -O labels_map_fixed.txt
```
### Command
```
$ sudo python ./tpu/models/official/efficientnet/eval_ckpt_main.py --model_name={model_name} --ckpt_dir={model_name} --example_img=panda.jpg --labels_map_file=labels_map_fixed.txt
```
### Error log
```
2021-03-11 09:03:09.865889: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-03-11 09:03:12.080250: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-11 09:03:12.082160: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-03-11 09:03:12.093261: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-03-11 09:03:12.093330: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (35c1c0e66ebe): /proc/driver/nvidia/version does not exist
2021-03-11 09:03:12.094005: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-11 09:03:18.928853: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
2021-03-11 09:03:18.960335: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2299995000 Hz
Traceback (most recent call last):
  File "./tpu/models/official/efficientnet/eval_ckpt_main.py", line 121, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "./tpu/models/official/efficientnet/eval_ckpt_main.py", line 110, in main
    FLAGS.export_ckpt)
  File "/content/tpu/models/official/efficientnet/utils.py", line 531, in eval_example_images
    ckpt_dir, image_files, [0] * len(image_files), enable_ema, export_ckpt)
  File "/content/tpu/models/official/efficientnet/utils.py", line 497, in run_inference
    self.restore_model(sess, ckpt_dir, enable_ema, export_ckpt)
  File "/content/tpu/models/official/efficientnet/utils.py", line 434, in restore_model
    saver.restore(sess, checkpoint)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/saver.py", line 1285, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
```
### Debug attempt
When I tried to debug the error message in utils.py at line 434, it seemed like something was wrong with the Tensorflow training function a few lines above, since it always returned `none`.  
```
421    print(ckpt_dir) # --> efficientnet-lite1 
422    checkpoint = tf.train.latest_checkpoint(ckpt_dir)
423    print(checkpoint) # --> none
```

**Comment by BaderTim** [comment]
It seems like this error is not only occuring on efficientnet lite, but also on the default efficientnet models B6, B8, L2 (might be even more, but I tested it with those)

**Comment by AshleyRZ** [comment]
Move the content in line 421(checkpoint = tf.train.latest_checkpoint(ckpt_dir)) to line 434. Done.
