### ISSUE TITLE
MRCNN SpineNet-190 checkpoint & inference broken

### ISSUE THREAD

**Issue by raj-shah** [tensorflow/tpu#913]
Following [GETTING_STARTED.md](https://github.com/tensorflow/tpu/blob/master/models/official/detection/GETTING_STARTED.md) and #770, I am running the following for inference using SpineNet-190 on the instance segmentation task:
```
MODEL="mask_rcnn"
CHECKPOINT_PATH="/home/rajshah/tpu/spinenet-190/model.ckpt-187600"
CONFIG_PATH="/home/rajshah/tpu/models/official/detection/configs/spinenet/spinenet190_mrcnn.yaml"
LABEL_MAP_FILE="/home/rajshah/tpu/models/official/detection/datasets/coco_label_map.csv"
IMAGE_FILE_PATTERN="/home/rajshah/datasets/coco/test2017/000000200433.jpg"
OUTPUT_HTML="./test.html"
python ~/tpu/models/official/detection/inference.py \
  --model="${MODEL?}" \
  --config_file=${CONFIG_PATH?} \
  --checkpoint_path="${CHECKPOINT_PATH?}" \
  --label_map_file="${LABEL_MAP_FILE?}" \
  --image_file_pattern="${IMAGE_FILE_PATTERN?}" \
  --output_html="${OUTPUT_HTML?}"  
```

Similar to #770, and after many (deprecation) warnings, the script throws the following errors re a missing layer - `rpn_head/rpn-1/bias` - in the given checkpoint:

```
 - Loading the checkpoint...
INFO:tensorflow:Restoring parameters from /home/rajshah/tpu/spinenet-190/model.ckpt-187600
I0501 12:22:26.732679 139886229890880 saver.py:1284] Restoring parameters from /home/rajshah/tpu/spinenet-190/model.ckpt-187600
2021-05-01 12:22:29.629466: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key rpn_head/rpn-1/bias not found in checkpoint
Traceback (most recent call last):
  File "/home/rajshah/miniconda3/envs/tpu/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/rajshah/miniconda3/envs/tpu/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/rajshah/miniconda3/envs/tpu/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key rpn_head/rpn-1/bias not found in checkpoint
         [[{{node save/RestoreV2}}]]

.
.

Traceback (most recent call last):
  File "/home/rajshah/miniconda3/envs/tpu/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1300, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/home/rajshah/miniconda3/envs/tpu/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1618, in object_graph_key_mapping
    object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
  File "/home/rajshah/miniconda3/envs/tpu/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 915, in get_tensor
    return CheckpointReader_GetTensor(self, compat.as_bytes(tensor_str))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

.
.

tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please 
ensure that you have not altered the graph expected based on the checkpoint. Original error:
Key rpn_head/rpn-1/bias not found in checkpoint
         [[node save/RestoreV2 (defined at /miniconda3/envs/tpu/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
``` 

I also could not find said layer in the checkpoint (using `inspect_checkpoint.py`).

Any help greatly appreciated!
@xianzhidu @pengchongjin

**Comment by raj-shah** [comment]
Working with branch `r.2.2.0`
