### ISSUE TITLE
copy-paste inference error: Not found: Key efficientnet-b7/head/conv2d/kernel not found in checkpoint

### ISSUE THREAD

**Issue by wswdx** [tensorflow/tpu#925]
I try to run inference with configs and checkpoint file of "Cascade Eff-B7 NAS-FPN (1280) w/ self-training Copy-Paste".
But I got the following error at Line. 152: "saver.restore(sess, FLAGS.checkpoint_path)":

```
 - Loading the checkpoint...
INFO:tensorflow:Restoring parameters from ./pretrains/cnp/model.ckpt-300000
I0606 02:35:42.155469 139871970408256 saver.py:1284] Restoring parameters from ./pretrains/cnp/model.ckpt-300000
2021-06-06 02:35:48.569697: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key efficientnet-b7/head/conv2d/kernel not found in checkpoint
Traceback (most recent call last):
  File "/gruntdata/weidongxu.wdx/anaconda3/envs/tf115/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/gruntdata/weidongxu.wdx/anaconda3/envs/tf115/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/gruntdata/weidongxu.wdx/anaconda3/envs/tf115/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.**NotFoundError: Key efficientnet-b7/head/conv2d/kernel not found in checkpoint
         [[{{node save/RestoreV2}}]]**
```

Why did this happen? Could you please help me out? Thanks!

**Comment by jasonbunk** [comment]
To the "[efficientnet_builder.build_model()](https://github.com/tensorflow/tpu/blob/1ebfc4b5fa6b5fad0bd7d422832ae8826e8059f2/models/official/detection/modeling/architecture/efficientnet.py#L53-L57)" in "modeling/architecture/efficientnet.py", I think you need to add the argument `features_only=True` since the provided checkpoints have no weights for `efficientnet-b7/head`
