### ISSUE TITLE
[retinanet] Error when training custom dataset

### ISSUE THREAD

**Issue by fabito** [tensorflow/tpu#93]
Hi,

I'm trying to train retinanet on my own dataset.
The `tf records` were already generated for the object detection api which apparently uses the same `tf_example` format used here.

Any help is appreciated.

See below the traceback:

```
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:TPU job name tpu_worker
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Init TPU system
INFO:tensorflow:Start infeed thread controller
INFO:tensorflow:Start outfeed thread controller
INFO:tensorflow:Starting infeed thread controller.
INFO:tensorflow:Starting outfeed thread controller.
INFO:tensorflow:Enqueue next (100) batch(es) of data to infeed.
INFO:tensorflow:Dequeue next (100) batch(es) of data from outfeed.
Traceback (most recent call last):
  File "tpu/models/official/retinanet/retinanet_main.py", line 244, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "tpu/models/official/retinanet/retinanet_main.py", line 160, in main
    FLAGS.train_batch_size))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 352, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 891, in _train_model
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 546, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1022, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1113, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1098, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1170, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 950, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Gradient for resnet50/batch_normalization_50/gamma:0 is NaN : Tensor had NaN values
	 [[Node: CheckNumerics_151 = CheckNumerics[T=DT_FLOAT, message="Gradient for resnet50/batch_normalization_50/gamma:0 is NaN", _device="/job:tpu_worker/replica:0/task:0/device:CPU:0"](Identity_577)]]

Caused by op u'CheckNumerics_151', defined at:
  File "tpu/models/official/retinanet/retinanet_main.py", line 244, in <module>
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "tpu/models/official/retinanet/retinanet_main.py", line 160, in main
    FLAGS.train_batch_size))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 352, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 812, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 793, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2091, in _model_fn
    update_ops = _sync_variables_ops()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 129, in _sync_variables_ops
    for v in variables.trainable_variables()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 498, in check_numerics
    "CheckNumerics", tensor=tensor, message=message, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Gradient for resnet50/batch_normalization_50/gamma:0 is NaN : Tensor had NaN values
	 [[Node: CheckNumerics_151 = CheckNumerics[T=DT_FLOAT, message="Gradient for resnet50/batch_normalization_50/gamma:0 is NaN", _device="/job:tpu_worker/replica:0/task:0/device:CPU:0"](Identity_577)]]
```

**Comment by rjpower** [comment]
fabito, it's hard to say without knowing more about your data.  Have you used this dataset with the object detection API successfully?  I believe the object detection API will have TPU support soon, and we might have better support for models in the objection detection API.  A few thoughts:

* Have you adjusted the number of classes output by the model to match your training data (`--hparams=num_classes=XX`)?

* If the number of classes is correct, you can try adjusting the learning rate down (`--hparams=learning_rate=0.01`).  To specify multiple hparams, separate them with commas: `--hparams=learning_rate=0.04,num_classes=XX`.

Another possibility is that your input images don't have the same mean and variance as the ImageNet data.  You can turn on batch normalization training (`--hparams=is_training_bn=True`) to see if that helps as well.

**Comment by fabito** [comment]
@rjpower ,

I'm trying to train a face detector using the wider face dataset.

* Yes, I successfully trained a few different models using this exact same `tf record`
* I did adjust the `num_classes` hparam

BTW, this is the command I used:

```
python tpu/models/official/retinanet/retinanet_main.py \
 --master=${GRPC_SERVER} \
 --train_batch_size=64 \
 --training_file_pattern=${GCS_BUCKET}/widerface/tf_records/widerface_train.record \
 --resnet_checkpoint=${RESNET_CHECKPOINT} \
 --model_dir=${MODEL_DIR} \
 --hparams=image_size=640,num_classes=1, \
 --num_examples_per_epoch=12880 \
 --num_epochs=1
```

I'll try the other suggestions.

**Comment by aman2930** [comment]
Hi Fabito,
Just want to check if you are able to resolve this.

**Comment by kulkarnivishal** [comment]
@aman2930 were you able to solve this?

**Comment by NielsLindberg** [comment]
Hey,

I had this error when training Densenet on a custom tfrecords dataset. Fixed it by changing batch_size from 1024 to 256. Not really sure why that fixed it. Maybe it was trying to load from a shard that had < batch_size records resulting in NaN's for the remainders. But then its kinda wierd that you get the error with 64 train batchsize.
