### ISSUE TITLE
Issue while training "attribute_mask_rcnn" or "mask_rcnn" model.

### ISSUE THREAD

**Issue by janmejaya-nanda** [tensorflow/tpu#956]
I am using fashionpedia dataset and converting them to tfrecord using [create_coco_tf_record.py](https://github.com/tensorflow/tpu/blob/master/tools/datasets/create_coco_tf_record.py)(without mask). Then using those tfrecord to train different models (mask_rcnn, attribute_mask_rcnn, retinanet etc).
command to train:
`python3 tpu/models/official/detection/main.py --model="retinanet" --model_dir=<dir to save models> --mode=train --eval_after_training=True --use_tpu=False --params_override="{ train: { train_file_pattern: <path to train tfrecord> }, eval: { val_json_file: <path>/instances_attributes_val2020.json , eval_file_pattern: <path to eval tfrecord>} }"`

I am able to successfully train for "retinanet" model but my training process fails with bellow error when I change `--model` to either "mask_rcnn" or "attribute_mask_rcnn". (I am only changing "model" param rest(including tfrecord) are kept the same.)
training process fails with:
`Parsing Inputs...
Traceback (most recent call last):
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: {{function_node __inference_Dataset_map_<class 'dataloader.maskrcnn_parser.Parser'>_2124}} indices[7] = 7 is not in [0, 0)
	 [[{{node parser/GatherV2_2}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
	 [[ArithmeticOptimizer/AddOpsRewrite_add_5/_9827]]
  (1) Invalid argument: {{function_node __inference_Dataset_map_<class 'dataloader.maskrcnn_parser.Parser'>_2124}} indices[7] = 7 is not in [0, 0)
	 [[{{node parser/GatherV2_2}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/impact/Documents/attribute-smart/tpu/models/official/detection/main.py", line 184, in <module>
    tf.app.run(main)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/impact/Documents/attribute-smart/tpu/models/official/detection/main.py", line 140, in main
    executor.train(train_input_fn, params.train.total_steps)
  File "/home/impact/Documents/attribute-smart/tpu/models/official/detection/executor/tpu_executor.py", line 145, in train
    self._estimator.train(input_fn=input_fn, max_steps=steps)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1159, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1222, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1333, in _actual_train_model_distributed
    saving_listeners)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1494, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/training/monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/impact/.virtualenv/attribute-smart-tpu/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: {{function_node __inference_Dataset_map_<class 'dataloader.maskrcnn_parser.Parser'>_2124}} indices[7] = 7 is not in [0, 0)
	 [[{{node parser/GatherV2_2}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
	 [[ArithmeticOptimizer/AddOpsRewrite_add_5/_9827]]
  (1) Invalid argument: {{function_node __inference_Dataset_map_<class 'dataloader.maskrcnn_parser.Parser'>_2124}} indices[7] = 7 is not in [0, 0)
	 [[{{node parser/GatherV2_2}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.`

initially, I tried to rectify my tfrecord as suggested [here](https://github.com/tensorflow/tensorflow/issues/17353) but, none of them worked out for me. Latter while training for "retinanet", realized its failing for only "attribute_mask_rcnn" or "mask_rcnn". 
I am not sure what causing this any help regarding the issue will be highly appreciated.

**Comment by mithileshrepo** [comment]
Hi I am getting below error while training 'attribute_mask_rcnn' model while training on fashionpedia dataset using tfrecord files.Please help.


------------------------------------


  File "/Users/mithilesh/miniforge3/envs/fashionpedia_env/lib/python3.8/site-packages/tensorflow/python/training/monitored_session.py", line 786, in run
    return self._sess.run(
  File "/Users/mithilesh/miniforge3/envs/fashionpedia_env/lib/python3.8/site-packages/tensorflow/python/training/monitored_session.py", line 1315, in run
    return self._sess.run(
  File "/Users/mithilesh/miniforge3/envs/fashionpedia_env/lib/python3.8/site-packages/tensorflow/python/training/monitored_session.py", line 1420, in run
    raise six.reraise(*original_exc_info)
  File "/Users/mithilesh/miniforge3/envs/fashionpedia_env/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/Users/mithilesh/miniforge3/envs/fashionpedia_env/lib/python3.8/site-packages/tensorflow/python/training/monitored_session.py", line 1405, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/mithilesh/miniforge3/envs/fashionpedia_env/lib/python3.8/site-packages/tensorflow/python/training/monitored_session.py", line 1473, in run
    outputs = _WrappedSession.run(
  File "/Users/mithilesh/miniforge3/envs/fashionpedia_env/lib/python3.8/site-packages/tensorflow/python/training/monitored_session.py", line 1236, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/mithilesh/miniforge3/envs/fashionpedia_env/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 970, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/Users/mithilesh/miniforge3/envs/fashionpedia_env/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1193, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/Users/mithilesh/miniforge3/envs/fashionpedia_env/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1373, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/Users/mithilesh/miniforge3/envs/fashionpedia_env/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1399, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = 0 is not in [0, 0)
	 [[{{node parser/GatherV2_1}}]]
	 [[MultiDeviceIteratorGetNextFromShard]]
	 [[RemoteCall]]
	 [[IteratorGetNext]]
