### ISSUE TITLE
Error occurred during infeed/outfeed when training Mobilenet on ImageNet

### ISSUE THREAD

**Issue by Sixigma** [tensorflow/tpu#96]
Hi , I got error report when I try to conduct training of TPU Mobilenet :

```
INFO:tensorflow:Using config: {'_tpu_config': TPUConfig(iterations_per_loop=100, num_shards=1, per_host_input_for_training=True, tpu_job_name=None, initial_infeed_sleep_secs=None), '_save_checkpoints_secs': 1000, '_session_config': allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_tf_random_seed': None, '_task_type': 'worker', '_global_id_in_cluster': 0, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fc4d0afa1d0>, '_model_dir': '/home/simon_lee/imagenet_train', '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_master': u'grpc://10.240.1.2:8470', '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_evaluation_master': u'grpc://10.240.1.2:8470', '_service': None, '_save_summary_steps': 100, '_num_ps_replicas': 0}
INFO:tensorflow:Starting training cycle 0.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/losses/losses_impl.py:731: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

INFO:tensorflow:Using RMS optimizer
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:TPU job name tpu_worker
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Init TPU system
INFO:tensorflow:Start infeed thread controller
INFO:tensorflow:Starting infeed thread controller.
INFO:tensorflow:Start outfeed thread controller
INFO:tensorflow:Starting outfeed thread controller.
INFO:tensorflow:Enqueue next (100) batch(es) of data to infeed.
INFO:tensorflow:Dequeue next (100) batch(es) of data from outfeed.
WARNING:tensorflow:

Error occurred during infeed/outfeed.  This may be due to a compile error in the main session.  Waiting for a short time for the main session to come back.

File system scheme '[local]' not implemented (file: 'train-*')
         [[Node: TensorSliceDataset/input_pipeline_task0/MatchingFiles = MatchingFiles[](TensorSliceDataset/input_pipeline_task0/MatchingFiles/pattern)]]
         [[Node: input_pipeline_task0/OneShotIterator = OneShotIterator[container="", dataset_factory=_make_dataset_a4fcf249[], output_shapes=[[160,160,160,3], [160]], output_types=[DT_FLOAT, DT_INT32], shared_name="", _device="/job:tpu_worker/replica:0/task:0/device:CPU:0"]()]]
ERROR:tensorflow:Feed error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 666, in _run_infeed
    session.run(self._enqueue_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
UnimplementedError: File system scheme '[local]' not implemented (file: 'train-*')
         [[Node: TensorSliceDataset/input_pipeline_task0/MatchingFiles = MatchingFiles[](TensorSliceDataset/input_pipeline_task0/MatchingFiles/pattern)]]
         [[Node: input_pipeline_task0/OneShotIterator = OneShotIterator[container="", dataset_factory=_make_dataset_a4fcf249[], output_shapes=[[160,160,160,3], [160]], output_types=[DT_FLOAT, DT_INT32], shared_name="", _device="/job:tpu_worker/replica:0/task:0/device:CPU:0"]()]]

ERROR:tensorflow:Closing session.  A RuntimeError should follow.
INFO:tensorflow:An error was raised. This may be due to a preemption in a connected worker or parameter server. The current session will be closed and a new session will be created. Error: Socket closed
INFO:tensorflow:Graph was finalized.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 647, in _cancel_session
    session.close()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 702, in close
    tf_session.TF_CloseDeprecatedSession(self._session, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
UnavailableError: Socket closed

INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Init TPU system
INFO:tensorflow:Start infeed thread controller
INFO:tensorflow:Starting infeed thread controller.
INFO:tensorflow:Start outfeed thread controller
INFO:tensorflow:Starting outfeed thread controller.
WARNING:tensorflow:Feed error occurred, terminating session.
```

The command I input :
```
python mobilenet.py \
--dataset_dir gs://imagenet \
--model_dir gs://imagenet_train \
--train_batch_size 160 \
--mode train_and_eval \
--depth_multiplier 0.50 \
--width 160 \
--height 160 \
--use_annotated_bbox True \
--num_classes=1001 \
--learning_rate 0.01 \
--tpu_name demo-tpu
```
I am also sure that the TPU has connected to GCS since the log can be seen in gs://imagenet_train ,
which is via adding TPU service account into IAM Member as Roles of "Storage Object Admin", "Log Writer", and "Viewer" , as documents mentioned.

Here is components I've installed :
```
Your current Cloud SDK version is: 194.0.0
The latest available version is: 194.0.0

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                  Components                                                 │
├───────────────┬──────────────────────────────────────────────────────┬──────────────────────────┬───────────┤
│     Status    │                         Name                         │            ID            │    Size   │
├───────────────┼──────────────────────────────────────────────────────┼──────────────────────────┼───────────┤
│ Not Installed │ App Engine Go Extensions                             │ app-engine-go            │ 151.9 MiB │
│ Not Installed │ Cloud Bigtable Command Line Tool                     │ cbt                      │   4.5 MiB │
│ Not Installed │ Cloud Bigtable Emulator                              │ bigtable                 │   3.7 MiB │
│ Not Installed │ Cloud Datalab Command Line Tool                      │ datalab                  │   < 1 MiB │
│ Not Installed │ Cloud Datastore Emulator                             │ cloud-datastore-emulator │  17.9 MiB │
│ Not Installed │ Cloud Datastore Emulator (Legacy)                    │ gcd-emulator             │  38.1 MiB │
│ Not Installed │ Cloud Pub/Sub Emulator                               │ pubsub-emulator          │  33.4 MiB │
│ Not Installed │ Emulator Reverse Proxy                               │ emulator-reverse-proxy   │  14.5 MiB │
│ Not Installed │ Google Container Local Builder                       │ container-builder-local  │   3.8 MiB │
│ Not Installed │ Google Container Registry's Docker credential helper │ docker-credential-gcr    │   3.3 MiB │
│ Not Installed │ gcloud app Java Extensions                           │ app-engine-java          │ 118.9 MiB │
│ Not Installed │ gcloud app PHP Extensions                            │ app-engine-php           │           │
│ Not Installed │ gcloud app Python Extensions                         │ app-engine-python        │   6.2 MiB │
│ Not Installed │ gcloud app Python Extensions (Extra Libraries)       │ app-engine-python-extras │  27.8 MiB │
│ Not Installed │ kubectl                                              │ kubectl                  │  12.3 MiB │
│ Installed     │ BigQuery Command Line Tool                           │ bq                       │   < 1 MiB │
│ Installed     │ Cloud SDK Core Libraries                             │ core                     │   7.4 MiB │
│ Installed     │ Cloud Storage Command Line Tool                      │ gsutil                   │   3.4 MiB │
│ Installed     │ gcloud Alpha Commands                                │ alpha                    │   < 1 MiB │
│ Installed     │ gcloud Beta Commands                                 │ beta                     │   < 1 MiB │
└───────────────┴──────────────────────────────────────────────────────┴──────────────────────────┴───────────┘
To install or remove components at your current SDK version [194.0.0], run:
  $ gcloud components install COMPONENT_ID
  $ gcloud components remove COMPONENT_ID

To update your SDK installation to the latest version [194.0.0], run:
  $ gcloud components update
```

The ImageNet tfrecord files are produced from tfslim script , and work smoothly on slim.
Any suggestions on this problem ? Thank you.

**Comment by saeta** [comment]
Hey @Sixigma ,

I believe the salient error you're encountering is:

```
File system scheme '[local]' not implemented (file: 'train-*')
         [[Node: TensorSliceDataset/input_pipeline_task0/MatchingFiles = MatchingFiles[](TensorSliceDataset/input_pipeline_task0/MatchingFiles/pattern)]]
```

It looks like you're trying to perform a glob expansion of a non-GCS file system on your Cloud TPU (i.e. the `[local]` file system). I think the issue might be the flag values you're using. From [`moblenet.py#L62`](https://github.com/tensorflow/tpu/blob/master/models/official/mobilenet/mobilenet.py#L62) it looks like the right flag value is `--data_dir` (as opposed to `--dataset_dir`).

That said, I also looked through the rest of your log, and it looks like there's at least one other issue. From:

```
INFO:tensorflow:Using config: {'_tpu_config': TPUConfig(iterations_per_loop=100, num_shards=1, per_host_input_for_training=True, tpu_job_name=None, initial_infeed_sleep_secs=None), '_save_checkpoints_secs': 1000, '_session_config': allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_tf_random_seed': None, '_task_type': 'worker', '_global_id_in_cluster': 0, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fc4d0afa1d0>, '_model_dir': '/home/simon_lee/imagenet_train', '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_master': u'grpc://10.240.1.2:8470', '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_evaluation_master': u'grpc://10.240.1.2:8470', '_service': None, '_save_summary_steps': 100, '_num_ps_replicas': 0}
```

it looks like your model directory is not being set correctly. (From above: `_model_dir': '/home/simon_lee/imagenet_train'` likely indicates you're going to run into some issues once you resolve your input pipeline source files.)

Hope that helps!

**Comment by Sixigma** [comment]
Sorry for my careless , I would close this issue , thank you .
